### ISSUE TITLE
use ${ZDOTDIR} for custom installation folder

### ISSUE THREAD

**Issue by smenzer** [romkatv/zsh4humans#1]
First of all..this is amazing and exactly what I've been looking for!

Can I recommend that instead of using `~/.zshrc` and `~/.cache`, that you instead use `${ZDOTDIR}/*`? I want to keep my files out of the home directory and right now I have to manually change your script, which means if/when you update, it will break.

**Comment by romkatv** [comment]
> First of all..this is amazing and exactly what I've been looking for!

Thanks!

> Can I recommend that instead of using `~/.zshrc` and `~/.cache`, that you instead use `${ZDOTDIR}/*`?

The script doesn't hard-code neither of these paths, except in one error message. You can totally define `ZDOTDIR` and store your `.zshrc` in `$ZDOTDIR/.zshrc`.

Cache is stored in `${Z4H_DIR:-${XDG_CACHE_HOME:-~/.cache}/zsh4humans}`. The fallback to `${XDG_CACHE_HOME:-~/.cache}` is the right thing to do because it's a cache. You can remove it any time without breaking anything. `$ZDOTDIR` isn't appropriate location for caches.

**Comment by smenzer** [comment]
Fair enough on `.cache`. I had moved my `.zhistory` inside of my zdotdir, too, which is also hardcoded. I guess you'd make the same point about this file as .cache?

The other place it's used is here:
```

# Initialize prompt. Type `p10k configure` or edit ~/.p10k.zsh to customize it.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
source $Z4H_DIR/romkatv/powerlevel10k/powerlevel10k.zsh-theme
```

this means when i "reinstall" your `.zshrc` file, it forces me to rerun the p10k initialization, which at the end, adds the follow line to the bottom of your file:

```

# To customize prompt, run `p10k configure` or edit ~/zdotdir/.p10k.zsh.
[[ ! -f ~/zdotdir/.p10k.zsh ]] || source ~/zdotdir/.p10k.zsh
```

Not the end of the world, but a little annoying to have to go and update to add this.

**Comment by romkatv** [comment]
I've overlooked the fact that the directory for `.zsh_history` and `.p10k.zsh` is hard-coded. Thanks for pointing it out. Fixed.

**Comment by smenzer** [comment]
cool, thanks!
