### ISSUE TITLE
Mac OS 11.4 Clean Install

### ISSUE THREAD

**Issue by Onfroygmx** [romkatv/zsh4humans#116]
Hello,

First of all great job for all that you are offering !!
I did a clean install of Big Sur  macos 11.4 today and decided to give zsh4humans v5 a try.

2 issues:
- The install process can not be completed in 1 run. In order to have the fonts working the terminal app needs to be restarted with the correct font settings or else the usual question marks appear ( Already present with v4, it's a mac issue)
- Maybe because of previous error during installation, it seems an env variable is missing.
  When starting the terminal the created .zsh* are not sourced, but after restarting the shell in the terminal the correct files are sourced:

```
^[[?1;2c(anon):39: bad math expression: operator expected at `1'
onf@Onfs-MacBook-Pro ~
% zsh 
z4h recovery mode
  ~ ····························································································································································································································································  21:41:49 ─╮
❯ 
❯ which zsh
/bin/zsh
❯ zsh --version
zsh 5.8 (x86_64-apple-darwin20.0)

```

[env.txt](https://github.com/romkatv/zsh4humans/files/6565260/env.txt)
[fpath.txt](https://github.com/romkatv/zsh4humans/files/6565261/fpath.txt)

I can retest it the next few days as for the moment I'm reconfiguring everything, but a clean install takes a day (very slow internet conection).
No other issue noticed so far.

**Comment by Onfroygmx** [comment]
Update: By default on big sur run commands are not executed on startup
tmux -u -S /tmp/z4h-tmux-501-xterm-256color-1622289076.7808589935 -f ~/.cache/zsh4humans/v5/zsh4humans/tmux-256color.conf

Once enabled and terminal app restarted defaults are loaded

**Comment by romkatv** [comment]
> Update: By default on big sur run commands are not executed on startup

What does this mean? Can you clarify?

> tmux -u -S /tmp/z4h-tmux-501-xterm-256color-1622289076.7808589935 -f ~/.cache/zsh4humans/v5/zsh4humans/tmux-256color.conf

What are you trying to say by posting this command?

> Once enabled and terminal app restarted defaults are loaded

Enabled what? Which defaults?

**Comment by Onfroygmx** [comment]
What does this mean? Can you clarify?
Well apple has locked down the system to work as an IPhone so all the settings done through cmd line don't work like they used to be.
If I install the fonts manually and enable them your install works fine, not if I use the installer.
If I don't enable the command shell manually it will not be loaded see screenshot:
![shellcmds](https://user-images.githubusercontent.com/25054585/120102625-6e23c000-c13b-11eb-9ad9-c8fc7f0eac0e.png)

What does this mean? Can you clarify?
I'm trying to help not to blame...

**Comment by romkatv** [comment]
> Well apple has locked down the system to work as an IPhone so all the settings done through cmd line don't work like they used to be.

Were you trying to change settings of something through command line? Which settings were that and which commands were you executing to change them?

> If I install the fonts manually and enable them your install works fine, not if I use the installer.

The installer doesn't attempt to install any fonts if you run it from Apple Terminal. Moreover, Fonts used by Apple Terminal have no effect on what the installer does.

Did you see any indication of the installer trying to install fonts? Did it ask you whether to install fonts? Did it say it's installing fonts?

> If I don't enable the command shell manually it will not be loaded see screenshot:
> ![shellcmds](https://user-images.githubusercontent.com/25054585/120102625-6e23c000-c13b-11eb-9ad9-c8fc7f0eac0e.png)

The "Run command" looks very strange. Did you manually set it? Why?

> The install process can not be completed in 1 run. In order to have the fonts working the terminal app needs to be restarted with the correct font settings or else the usual question marks appear ( Already present with v4, it's a mac issue)

What does "can not be completed in 1 run" mean? Did it fail? did it produce errors?

> In order to have the fonts working the terminal app needs to be restarted with the correct font settings or else the usual question marks appear

Please clarify. Are you saying that after you've changed the font in Apple Terminal, you had to manually restart Apple Terminal for your changes to have effect? I've never seen this before. If this is true, that would be a bug in Apple Terminal.

> I'm trying to help not to blame...

I'm grateful. I'm not saying you are doing anything wrong. I'm asking for more information so that I understand what you are doing and what you are observing. The original issue description is vague, so I have to ask questions.

I see on the first line of your your original screenshot some errors. What did you do prior to that?

**Comment by Onfroygmx** [comment]
The original screeenshot is just starting the termial app.
What I did:
Clean install Big Sur and then my first command:
sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"

I tried it on an arch install and nothing of this happened so it is purely mac os related.

For the fonts if you don't specify them explicitly terminal.app won't use them even after intstall.
![fonts](https://user-images.githubusercontent.com/25054585/120105760-e98c6e00-c149-11eb-9418-eb8e8be8d750.png)

The run command is yours, just enabled it, no change. I don't use tmux.
Having these steps does not able to make it work in 1 run, while it works on arch/linux.

Again this is purely a macos X ++ problem, encountered on a clean install with nothing else defined.

I agree the bugs are in apple ( security), not your code. It's just zsh4humans not apples :)

**Comment by romkatv** [comment]
> The original screeenshot is just starting the termial app.
> What I did:
> Clean install Big Sur and then my first command:
> sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"

At the very end this command should've run powerlevel10k configuration wizard where you need to answer many questions about prompt. The first questions ("does it look like a diamond", etc.) are meant to establish the capabilities of your terminal's font (can it display powerline glyphs? can it display nerdfont glyphs, etc.). If you answer those questions correctly (choose "no" on the first question if the image does not look like a diamond, etc.), prompt will not have question marks in it. The only way to get question marks in prompt is to abort powerlevel10k configuration wizard or to choose choose "yes" on questions where the true answer is "no".

You said earlier that you had question marks in prompt. Did the configuration wizard run? Did you answer the "does it look like" questions correctly?

> For the fonts if you don't specify them explicitly terminal.app won't use them even after intstall.
> ![fonts](https://user-images.githubusercontent.com/25054585/120105760-e98c6e00-c149-11eb-9418-eb8e8be8d750.png)

This is expected. The install script does not attempt to change Apple Terminal's fonts. It also does not assume that you are using a specific font. It does not assume that your font can display powerline glyphs or any other non-ascii glyphs.

> The run command is yours, just enabled it, no change. I don't use tmux.

Why did you change the default?

> Having these steps does not able to make it work in 1 run, while it works on arch/linux.
> 
> Again this is purely a macos X ++ problem, encountered on a clean install with nothing else defined.

I've executed the install script on a clean install of macOS Big Sur and didn't experience these problems. I'm still unsure what exactly you did and what happened when you did that. Hence more questions. Please bear with me.

> I agree the bugs are in apple ( security), not your code. It's just zsh4humans not apples :)

Before saying which component is to blame for bugs, I'd really like to understand what you did and what you observed so that I can see how the bugs you are referring to are manifested.

**Comment by romkatv** [comment]
> The original screeenshot is just starting the termial app.

After doing what? Please describe every step.

**Comment by Onfroygmx** [comment]
This is going nowhere.

clicking on terminal.app starts terminal.app ...
clicking on enable fonts, enable fonts
clicking on enable shell commands enables hell commands ...

rm -rf ~/.zsh4humans solves everything

Do you use a mac ?

**Comment by romkatv** [comment]
> This is going nowhere.
> 
> clicking on terminal.app starts terminal.app ...
> clicking on enable fonts, enable fonts
> clicking on enable shell commands enables hell commands ...
> 
> rm -rf ~/.zsh4humans solves everything

Sorry, I don't understand this.

> Do you use a mac ?

Yes. I'm trying to reproduce the "bad math expression" error but the instructions aren't specific enough. Here's where I'm at:

1. Factory-reset a macbook and go through the initial setup.
2. Open the Apple Terminal app.
3. Execute this command: `sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"`
4. ???
5. Open the Apple Terminal app.
6. Observe "bad math expression" error.

What goes in step 4?

If I understand correctly, you are also reporting that powerlevel10k displays unprintable characters (question marks) in prompt. What do I need to do to see them?

You've also change the default terminal command to something surprising. Why? Were you trying to find a workaround for some issue? Which issue? What do I need to do to see it on my own machine?
