### ISSUE TITLE
Basic autocompletion doesn't work?

### ISSUE THREAD

**Issue by colemickens** [romkatv/zsh4humans#12]
`systemctl --user restart gpg-agent<tab>` doesn't work.

`cd dir1<tab><down><tab>` doesn't... actually let you tab complete more than one dir at a tab.

It was very jarring to try and switch to zsh with this with my most used tab completions not working at all. Am I doing something wrong?

**Comment by romkatv** [comment]
> `systemctl --user restart gpg-agent<tab>` doesn't work.

In general Zsh has completions for more tools out of the box but there are a few tools for which completions work by default in Bash but not Zsh. To get `systemctl` completions, make two changes to `~/.zshrc`:

1. Add an extra element to `github_repos` array:
```zsh
local github_repos=(
  ...
  systemd/systemd  # https://github.com/systemd/systemd
)
```
2. Add an extra element to `fpath` array:
```zsh
fpath+=(... $Z4H_DIR/systemd/systemd/shell-completion/zsh)
```

Note that both of these arrays are already define. You need to add `systemd/systemd` to the first and `$Z4H_DIR/systemd/systemd/shell-completion/zsh` to the second.

> `cd dir1<tab><down><tab>` doesn't... actually let you tab complete more than one dir at a tab.

You can do `cd dir1<tab>`, choose the right entry from the list, and then hit `alt-enter` to accept the completion and trigger another completion immediately. This binding is set via `FZF_TAB_CONTINUOUS_TRIGGER` (you can find this parameter in `~/.zshrc`). It's popular to set it to `/` specifically to make completion of paths natural.

It's not obvious but when the completion menu shows up, you can type in there to restrict and order the list of options. The search syntax is documented in https://github.com/junegunn/fzf#search-syntax.

Specifically for `cd dir/...` it's usually more convenient to use `alt-down` shortcut. `alt-up`, `alt-left` and `alt-right` are also very convenient for changing your current directory.

In addition, when completing an argument that is a file path, you can use `ctrl-t` instead of `tab`. It allows you to complete the whole path in one go. You can also use `cd <ctrl-t>` or `cd /foo/<ctrl-t>`.

You can change these bindings by editing [this section of ~/.zshrc](https://github.com/romkatv/zsh4humans/blob/32a177912a290e403883b4e729b0b2c720cbd1a0/.zshrc#L326-L354)

> It was very jarring to try and switch to zsh with this

I'm sorry to hear that.

**Comment by colemickens** [comment]
Thank you so much for the detailed reply. I'll make my way through these and maybe write up some "quick start" tips, maybe that could be a useful thing I could contribute to the README since you wrote all of that up for me.

Thank you for taking the time, and thank you for powerlevel10k also! :).

**Comment by romkatv** [comment]
> I'll make my way through these and maybe write up some "quick start" tips, maybe that could be a useful thing I could contribute to the README since you wrote all of that up for me.

I really appreciate your offer :heart: 

I'm in the process of developing a new version of zsh4humans that is very different form the current. It'll come with an onboarding configuration wizard similar to powerlevel10k, which should help new users to get comfortable. Hopefully it'll make transition from other shells smoother than the rough experience you've had.

**Comment by romkatv** [comment]
Closing as I believe this issue is resolved. If not, please reopen.
