### ISSUE TITLE
Server exited unexpectedly in v5 on termux 

### ISSUE THREAD

**Issue by laraib07** [romkatv/zsh4humans#124]
I updated v5 on termux today. After installation, i get above error. 
Everything were working fine on v4.

![Screenshot_20210618-114725_Termux](https://user-images.githubusercontent.com/25507825/122516158-07a00c80-d02c-11eb-9459-f1a316801c90.png)
g

**Comment by romkatv** [comment]
How did you upgrade to v5?

What do you do to trigger the error on the screenshot?

**Comment by laraib07** [comment]
I was already on v4.
First i tried `z4h update` but it didn't updated to v5. Then I copy pasted the installation command from readme. After going through the setup part successfully, this occurred.

**Comment by romkatv** [comment]
> I was already on v4.
> First i tried `z4h update` but it didn't updated to v5.

This is expected. `z4h update` will never change the major version because major versions aren't backward compatible with user configs. That is, you cannot use the same `~/.zshrc` with v4 and v5.

> Then I copy pasted the installation command from readme. After going through the setup part successfully, this occurred.

You haven't modified `~/.zshrc` after the installation, right?

FWIW, I just tried installing v5 on my old Nexus 5X and it works fine. If rebooting your device doesn't help, consider switching back to v4. You can do that by restoring `~/.zshrc` and `~/.zshenv` from the backup (should be under `~/zsh-backup`).

**Comment by laraib07** [comment]
>You haven't modified ~/.zshrc after the installation, right?

I renamed my previous .zshrc to .zshrc.bak, as to fetch latest .zshrc from v5. 
Then I copy pasted the installation command. 
After setup, above mentioned error occurred. I haven't got any chance to edit it.

**Comment by romkatv** [comment]
Closing because I don't intend to debug this (sorry!). If you ever find out the culprit, please post an update.
