### ISSUE TITLE
SSH hangs after PC sleeps

### ISSUE THREAD

**Issue by logicbus** [romkatv/zsh4humans#126]
I've been using Z4H for a while. At least since v2.  

Recently I wanted to turn off Z4H's feature that copies the .zshrc file to the remote SSH host.  So I ran the install if statement from the readme and it looked like I went from v2 to v5.  

Since then, my .zshrc is not copied to the remote host, and that's good.  But it seems that if my computer goes to sleep while I'm connected to an SSH session (like when I close my laptop), then when I try to SSH (into the same host) after waking my PC, the SSH command just hangs.  

I think Z4H does something where, if you have one session connected to that host and you try to open another session, you don't have to enter your password?  I wonder if that's the problem?  It's trying to use that session but it doesn't exist anymore, so it hangs?  

If I can come up with more solid repro steps I'll add them

**Comment by romkatv** [comment]
I've changed the code so that control master is no longer used when ssh teleportation is disabled. Please run `z4h update` and see if it helps.

That said, control master is a great ssh feature and I highly recommend enabling it in your ssh config. You can enable auto-detection of dead TCP connections via `ServerAliveInterval` and `ServerAliveCountMax` (see `man ssh_config`). When you know the connection is dead (e.g., after awaking your PC), you can manually kill the control master with `ssh -O exit <hostname>` without having to wait for alive messages. See [my ssh config](https://github.com/romkatv/dotfiles-public/blob/master/.ssh/config) for an example.

**Comment by logicbus** [comment]
I ran `z4h update` and tested.  

On my Windows PC with WSL, definite improvement.  The terminal window that was connected before the PC went to sleep shows the "client_loop: send disconnect: Broken pipe" message, and after that I have my local prompt, where I can run the ssh command again or do anything normal.

On my Chromebook with Linux, after waking the Chromebook, the terminal panel that was connected before the Chromebook went to sleep appears to still be connected to the SSH session, but it doesn't accept/reflect any input.  Can't type `ls` or `pwd`, can't do ctrl-c.  

My WSL is Ubuntu and my ChromeOS Linus is Debian.  Could this be due to a difference between Ubuntu and Debian?

**Comment by romkatv** [comment]
After my fix `ssh` works in zsh4humans just like it normally does (assuming that you've disabled ssh teleportation). Naturally it hangs when the underlying TCP connection dies. See my previous comment for how to deal with it or google it. In addition to what I mentioned earlier, you can manually terminate an ssh connection at any time with <kbd>~ .</kbd> (tilde followed by dot). FWIW, in my ssh config I remap the escape char from <kbd>~</kbd> to <kbd>`</kbd> because it's much more common to start a real command with the former rather than the latter.

Closing as fixed.
