### ISSUE TITLE
double click a shell script in finder doesn't work.

### ISSUE THREAD

**Issue by atjshop** [romkatv/zsh4humans#128]
Script test.sh with one line:
`echo $(date) >> /tmp/tmp.txt`
change its permission to 700

when running in terminal: source ./test.sh, it works fine
however when I double click the test.sh in finder, it doesn't work. it opens iterm2, and spits out below error:
`(anon):39: bad math expression: illegal character: ^[`
and it shows 'zsh recovery mode'

sometimes it opens a terminal and stay there, didn't run the code.

If I switch to use oh-my-zsh, this script works in both terminal and double click it in finder. Seems to me something wrong in zsh4humans?

**Comment by romkatv** [comment]
When I double-click `test.sh`, it gets open in XCode. If I configure macOS to open `*.sh` files with iTerm2, then iTerm2 opens whenever I double-click `test.sh`. I don't get any errors. The script doesn't run though. It does run if I modify `~/.zshrc` like so:

```zsh
zstyle :z4h: start-tmux no
```

The fact that the script doesn't run is a bug. I think this needs to be fixed in tmux. When I get a free minute I'll report it upstream. Feel free to do it yourself if you know how to describe the issue without a reference to zsh4humans (this reference would make it very difficult for the tmux dev(s) to understand the issue).

When iTerm2 does looks very odd to me. I would expect it to execute the script directly as if it was specified through *Command* option within *Preferences -> General*. Instead, iTerm2 uses the default command and sends `/path/to/test.sh; exit` to its stdin. Quite bizarre. I don't know why iTerm2 does this. If it did the thing I expect, everything would work fine for you. When I get a free minute I'll report it upstream. Feel free to do it yourself if you know how to describe the issue without a reference to zsh4humans (this reference would make it very difficult for the iTerm2 dev(s) to understand the issue).

**Comment by romkatv** [comment]
> The fact that the script doesn't run is a bug. I think this needs to be fixed in tmux. When I get a free minute I'll report it upstream.

I've opened this issue: https://github.com/tmux/tmux/issues/2909
