### ISSUE TITLE
Best practises?

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#166]
Not really a bug, but some questions of best practises. I don't however see any other way to contact you listed (except bug reports).

1. The command `z4h` is defined in `.zshrc`, not `.zshenv`. This means it is not available if you want to batch run `ssh <host> z4h update`. I have a script that does this for all online dev machines when it comes to `chezmoi update`. What is the best way to do something like this? I guess using something like `tmux-cluster` to run many interactive command prompts with shared inputs could be an option, but I was hoping for something less interactive and more scriptable.
2. When developing the small change to zsh4humans the other day actually handling that was a bit awkward, having to test the change in one place and commit it in another. Is there a way to set up `z4h update` or similar to pull from a local git working directory instead? Or how do you set up the development environment when working on z4h? There is also the question of how script compilation interacts with all of this.

**Comment by romkatv** [comment]
> Not really a bug, but some questions of best practises. I don't however see any other way to contact you listed (except bug reports).

Issues are the preferred way to ask questions about z4h. All your questions and bug reports are great, even the ones that I don't fix (sorry!). Keep them coming.

---

**Re: updating z4h on a remote machine with a script.**

You can teleport z4h to a remote machine with a script like this:

```zsh
#!/usr/bin/env -S zsh -i

emulate -L zsh -o no_ignore_eof

ssh -t hostname <<<exit
```

The shebang says to execute this script with `zsh -i`, which makes `z4h` function available to it.

Run `z4h update` on your local machine before running this script. I've just fixed a bug that was preventing it from working.

To forcefully update z4h on the remote machine, replace the last line with this:

```zsh
ssh -t hostname <<<$'z4h update\nexit'
```

This shouldn't be necessary because ssh teleportation automatically updates z4h on the remote if your local rc files require a newer version of z4h than what's available there. When I add a new feature to z4h (a function, an alias, a zstyle, etc.), I bump [version](https://github.com/romkatv/zsh4humans/blob/v5/version). When teleporting, local version of z4h is sent over to the remote (it's the first part of `$Z4H_SSH`) and remote is updated if its version is lower. This is necessary because your local rc files might be using a feature of z4h that isn't available on the remote.

https://github.com/romkatv/zsh4humans/pull/165 should have bumped version but I overlooked this. I've bumped it now. If you now run `z4h update` on a local machine and then `ssh hostname` to a machine that already had z4h on it, you'll see that it's automatically updating. What it means is that it's enough to run `ssh -t hostname <<<exit` to update a remote if it needs updating. You only need to run `z4h update` on your local machine.

---

**Re: testing local changes to z4h.**

Put this in place of the similarly looking block in zshenv:

```zsh
Z4H_URL="https://raw.githubusercontent.com/romkatv/zsh4humans/v5"
: "${Z4H:=${XDG_CACHE_HOME:-$HOME/.cache}/zsh4humans/v5}"
[ -e ~/zsh4humans/z4h.zsh ] && Z4H_BOOTSTRAP_COMMAND='ln -s ~/zsh4humans "$Z4H_PACKAGE_DIR"'

umask o-w

if [ ! -e "$Z4H"/z4h.zsh ]; then
  mkdir -p -- "$Z4H" || return
  >&2 printf '\033[33mz4h\033[0m: fetching \033[4mz4h.zsh\033[0m\n'
  if [ -e ~/zsh4humans/z4h.zsh ]; then
    ln -sf -- ~/zsh4humans/z4h.zsh "$Z4H"/z4h.zsh || return
  else
    if command -v curl >/dev/null 2>&1; then
      curl -fsSL -- "$Z4H_URL"/z4h.zsh >"$Z4H"/z4h.zsh.$$ || return
    elif command -v wget >/dev/null 2>&1; then
      wget -O-   -- "$Z4H_URL"/z4h.zsh >"$Z4H"/z4h.zsh.$$ || return
    else
      >&2 printf '\033[33mz4h\033[0m: please install \033[32mcurl\033[0m or \033[32mwget\033[0m\n'
      return 1
    fi
    mv -- "$Z4H"/z4h.zsh.$$ "$Z4H"/z4h.zsh || return
  fi
fi
```

Run this:

```zsh
git clone https://github.com/VorpalBlade/zsh4humans.git ~/zsh4humans &&
  git -C ~/zsh4humans checkout v5 &&
  exec zsh
```

Run `z4h update`. Verify that you are now using a local version of zsh4humans:

```zsh
ls -ld -- $Z4H/{z4h.zsh,zsh4humans}
```

You should see that both of these are symlinks. If you now modify anything under `~/zsh4humans` you can apply these changes immediately with `exec zsh`. You don't need to run `z4h update` for that.

To switch back to the stock version of z4h, run this:

```zsh
rm -rf -- ~/zsh4humans && exec zsh
```

**Comment by romkatv** [comment]
Have you tried what I suggested? Does it work for you?

**Comment by VorpalBlade** [comment]
Hi, Unfortunately I will not be testing anything for a while. I got diagnosed with occupational burnout today, I will be taking a break from *everything* for a unknown period of time. Best of luck with your amazing project.

**Comment by romkatv** [comment]
Thanks for letting me know. I hope you get better soon.

I'll close your issues where I believe I've fixed stuff or answered your questions so that they don't sore my eyes and don't tempt you to do things you shouldn't be doing. Feel free to reopen them or open new ones when you bounce back.

**Comment by romkatv** [comment]
I believe I've answered all questions here. Closing.
