### ISSUE TITLE
Unable to install nodejs via asdf (via homebrew)

### ISSUE THREAD

**Issue by matschaffer** [romkatv/zsh4humans#169]
I ran into this issue today and am unsure where to apply the fix shown in https://github.com/asdf-vm/asdf-nodejs/issues/253#issuecomment-895466735

```
❯ asdf install nodejs 16.13.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4035    0  4035    0     0  36351      0 --:--:-- --:--:-- --:--:-- 36351
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.5M  100 28.5M    0     0  16.6M      0  0:00:01  0:00:01 --:--:-- 16.6M
node-v16.13.0-darwin-x64.tar.gz: OK
Unknown command: `asdf reshim nodejs 16.13.0`
/usr/local/Cellar/asdf/0.8.1_1/libexec/bin/asdf: line 82: /Users/matschaffer/.asdf/lib/commands/command-help.bash: No such file or directory
```

z4h has cloned a copy of https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/asdf/asdf.plugin.zsh#L7 which I tried updating on my disk, but it doesn't seem to have any effect.

I'm not using ohmyzsh to my knowledge, just a new macbook with homebrew-installed asdf and z4h installed via the readme snippet.

**Comment by matschaffer** [comment]
As a workaround I added `. "$(brew --prefix asdf)/libexec/asdf.sh"` to the bottom of my `~/.zshrc` but not sure if that's an ideal fix.

**Comment by romkatv** [comment]
> I'm not using ohmyzsh to my knowledge

In this case it's a good idea to remove ohmyzsh from your zshrc. Check out the comments.

```zsh
# [...] This is just an example. If you don't plan to use Oh My Zsh, delete this line.
z4h install ohmyzsh/ohmyzsh || return

[snip]

# This is just an example that you should delete. It does nothing useful.
z4h source ohmyzsh/ohmyzsh/lib/diagnostics.zsh  # source an individual file
z4h load   ohmyzsh/ohmyzsh/plugins/emoji-clock  # load a plugin
```

> As a workaround I added `. "$(brew --prefix asdf)/libexec/asdf.sh"` to the bottom of my `~/.zshrc` but not sure if that's an ideal fix.

When you need to install something, start by following the official installation instructions. In this case you want to install asdf. The instructions are here: https://asdf-vm.com/guide/getting-started.html. They list several installation methods. It seems like you've chosen Homebrew and already performed the first step:

```zsh
brew install asdf
```

And the second step:

```zsh
echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc
```

And now it works. So you've followed the instructions and everything works as advertised. There is no workaround involved. You did exactly what the docs said to do.

Now, with z4h you often can do things a bit more efficiently. In this case you can replace the line in zshrc with this:

```zsh
if [[ -n $HOMEBREW_PREFIX ]]; then
  z4h source -- $HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh
fi
```

Or this (more cryptic but shorter; otherwise equivalent):

```zsh
z4h source -- ${HOMEBREW_PREFIX:+$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh}
```

This change will bring the following benefits:

- It's about 3 times faster thanks to avoiding the call to `brew`. zsh4humans always sets `HOMEBREW_REPOSITORY`, `HOMEBREW_PREFIX` and `HOMEBREW_CELLAR` if you have `brew`.
- It won't produce errors on a machine without `brew`. This is important if you use ssh teleportation.
- It won't produce errors on a machine without asdf. This is important if you use ssh teleportation.

**Comment by matschaffer** [comment]
Awesome, thanks for the advice on a fast loading option.

The thing that had me thinking I needed an z4h change somewhere is that I'm getting _some_ integration with asdf without having to source `asdf.sh` (the command prompt icons & info).

And most other installations (golang, python) were working just fine without the source line.

I guess what I'm looking at here might just be an oddity of asdf that it can mostly work without sourcing, but not all plugins will.

**Comment by romkatv** [comment]
> The thing that had me thinking I needed an z4h change somewhere is that I'm getting _some_ integration with asdf without having to source `asdf.sh` (the command prompt icons & info).

Powerlevel10k can show asdf overrides even if asdf wasn't installed properly. Other than that there is no integration with asdf in zsh4humans. Maybe there should be.

> And most other installations (golang, python) were working just fine without the source line.
> 
> I guess what I'm looking at here might just be an oddity of asdf that it can mostly work without sourcing, but not all plugins will.

Right, that's how asdf works. This is not specific to zsh4humans.
