### ISSUE TITLE
No keys bound on fresh install

### ISSUE THREAD

**Issue by duog** [romkatv/zsh4humans#17]
HI, 
I'm really excited about your project.

I'm currently running a prezto zsh, and am trying out zsh4humans by cloning the repo and running
```
cd zsh4humans && ZDOTDIR=$(pwd) exec zsh
```

My terminal is kitty 0.15.0, I've tried xterm as well.

The p10k wizard runs, and the shell seems to work, with the exception that there are no z4h keys bound. `bindkey | grep z4h` gives no results.

I've tried setting ~/.zshenv to 
```
ZDOTDIR=~/zsh4humans
[[ -e $ZDOTDIR/.zshenv ]] && . $ZDOTDIR/.zshenv
```
and logging out/in 

Any idea what's happening?

**Comment by romkatv** [comment]
How do I reproduce this? Please post all commands I need to run.

**Comment by duog** [comment]
I have a test script 
```
#1 /usr/bin/env bash

XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}/doug-test/cache
mkdir -p $XDG_CACHE_HOME
cd $XDG_CACHE_HOME/..
[[ -e zsh4humans ]] || git clone https://github.com/romkatv/zsh4humans
ZDOTDIR=$(pwd)/zsh4humans
env -i bash -c "
export ZDOTDIR=$ZDOTDIR
export PATH=$PATH
export TERM=$TERM
export XDG_CACHE_HOME=$XDG_CACHE_HOME
echo \"env:\\n\$($which env)\\n------------\"
exec $(which zsh)
"
```
save and run this. press q to exit wizard
run `bindkey | grep z4h || echo "ohno"`

**Comment by romkatv** [comment]
This command doesn't reproduce it for me. Please either post instructions that reproduce the issue or figure out on your own what is going on.

By the way, your script has a few bugs. It also uses undocumented installation method for zsh4humans that isn't guaranteed to work. Keep in mind that may break at any moment, remove all your files, etc.

Here's a docker command that does what your script aims to do:

```zsh
docker run -e TERM -it --rm alpine sh -uec '
  cd
  apk add zsh
  wget https://raw.githubusercontent.com/romkatv/zsh4humans/master/.zshrc
  exec zsh'
```

The same thing but without system `zsh` (this emulates the case where you don't have recent enough version of `zsh` and cannot install it):

```zsh
docker run -e TERM -it --rm alpine sh -uec '
  cd
  wget https://raw.githubusercontent.com/romkatv/zsh4humans/master/.zshrc
  exec sh ~/.zshrc'
```

**Comment by duog** [comment]
I understand it's undocumented, but what is unsafe about it? Surely ZDOTDIR and XDG_CACHE_HOME should be respected.

FWIW I believe I understand the issue. On my OS /etc/zshenv sets VISUAL=vim. This causes the bindkey calls in z4h.zsh to go into the viins keymap.

I verify this with
```bash
#1 /usr/bin/env bash

REPRODUCE="${REPRODUCE:+1}"

if [[ -n "${REPRODUCE}" ]]; then
    editor=vim
else
    editor=emacs
fi

XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}/doug-test/cache
mkdir -p $XDG_CACHE_HOME
cd $XDG_CACHE_HOME/..
[[ -e zsh4humans ]] || git clone https://github.com/romkatv/zsh4humans
ZDOTDIR=$(pwd)/zsh4humans
cat > "$ZDOTDIR/.zshenv" <<__EOF__
setopt noglobalrcs
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
export EDITOR=$editor
export VISUAL=$editor

function print-z4h-binds() {
    for m in \$(bindkey -l); do bindkey -M \$m -L; done | grep z4h
}
__EOF__

env -i bash -c "
export ZDOTDIR=$ZDOTDIR
export PATH=$PATH
export TERM=$TERM
export XDG_CACHE_HOME=$XDG_CACHE_HOME
echo 'env:'
echo \"\$(env)\"
echo \"-------------\"
exec zsh -x" 2> "$XDG_CACHE_HOME/zsh4humans.stderr"
```

Enter a shell with either `REPRODUCE= ./test.sh` or `REPRODUCE=1 ./test.sh` and enter `print-z4h-binds` to see (some) z4h keybinds. With REPRODUCE=1 they are in the viins keymap, otherwise main and emacs.

**Comment by romkatv** [comment]
> I understand it's undocumented, but what is unsafe about it? Surely ZDOTDIR and XDG_CACHE_HOME should be respected.

I didn't mean `ZDOTDIR` or `XDG_CACHE_HOME`. `ZDOTDIR` is an environment variable understood by `zsh`, so it's respected as long as you use `zsh`. `XDG_CACHE_HOME` is understood by some software, so it's respected as long as you use said software.

I meant that the installation instructions for zsh4humans don't list `git clone` as an option. You are free to use the project in any way you like, just keep in mind that when using it in an undocumented way, all bets are off and no amount of damage should be outside of your expectations.

> The docker command does mostly work, except that my terminal (kitty) is not present in the terminfo db of the image.

Yeah, it sucks when your terminal uses an exotic terminfo entry that isn't a superset of anything standard such as xterm-256color. Harder to use docker, or to SSH to BSD servers or embedded Linux. By the way, if you are on Linux, VTE terminals are better at rendering zsh than Kitty. Try firing up GNOME terminal and comparing how p10k with transient prompt behaves. It's day and night. In GNOME, prompt is smooth. In kitty, it's jerky. If you aren't a fan of GNOME terminal, there are plenty of other VTE-based terminals.

If you need the exclusive features that kitty has, then kitty is the right choice. If you want a terminal that just works, VTE is better.

> FWIW I believe I understand the issue. On my OS /etc/zshenv sets VISUAL=vim.

Thanks! This is useful info.

zsh4humans currently doesn't work with vi keybindings very well. It's supposed to work with emacs bindings though. I've moved `bindkey -e` in zshrc above `z4h init` as a temporary measure. I'll implement a better solution when I add proper support for vi keymap.

**Comment by duog** [comment]
I see, yes I would change to `curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/master/.zshrc` if I were working further on this.

Thanks so much for your responses, fix and projects.

I like kitty for "url hinting" features, which look like vimium, if you're familiar. You can `kitty +kitten ssh` into a box and it will copy the terminfo. But thanks for your tip, I'll compare it. (transient prompt is a wonderful innovation btw!)

I noticed that my /etc/zshrc has loads of stuff in it (lots of completion configuration) which I don't think I want when using zsh4humans. My current thinking is that I likely do want /etc/{zprofile.zlogin,zlogout} in a portable config, so I intend to do that by setopting globalrcs in the appropriate places. Does that seem sensible to you?

**Comment by romkatv** [comment]
> I like kitty for "url hinting" features, which look like vimium, if you're familiar.

Kitty does have many great features.

I don't think you can open a URL printed to the terminal without using your mouse when using a VTE-based terminal. With a mouse it's quite easy though. URLs are automatically parsed and can be navigated to with ctrl-left-click.

![image](https://user-images.githubusercontent.com/1282067/81287615-5e829680-9063-11ea-976c-3cfd8e7713aa.png)

> You can `kitty +kitten ssh` into a box and it will copy the terminfo.

It works until it doesn't.

- If the target machine is a freebsd or windows box with default shell.
- If the source machine doesn't have `kitty`. For example, if you want to ssh from a remote machine, or if you want to ssh from a local container (docker, etc.).
- If the call to `ssh` is inside a script.

It's nice that `kitty +kitten ssh` exists but it's a partial workaround at best.

I guess it's a matter of priorities. It's important for me to have a terminal that just works without clutches. I also want smooth rendering. The extra features of Kitty don't outweigh the sacrifice in robustness and rendering appeal but that's likely because I've never gotten used to them.

FWIW, I believe that most Kitty users choose it because they mistakenly believe it's better than the default terminal. In fact, if you don't use the extra features, it's worse.

The disconnect between user expectations is more extreme with Alacritty. It has jerky rendering, exotic terminfo and fewer features than virtually any other terminal. Good marketing though. Borderline deceptive but certainly very effective.

> I noticed that my /etc/zshrc has loads of stuff in it (lots of completion configuration) which I don't think I want when using zsh4humans. My current thinking is that I likely do want /etc/{zprofile.zlogin,zlogout} in a portable config, so I intend to do that by setopting globalrcs in the appropriate places. Does that seem sensible to you?

In my own setup I use two zsh config files. `~/.zshenv` with just `setopt no_global_rcs` and `~/.zshrc` with everything else. All global rcs I've seen are either useless or harmful. I also don't recommend putting anything in `~/.zshenv` other than `setopt no_global_rcs` and don't recommend creating any other user rc files.
