### ISSUE TITLE
SSH teleport doesn't sync?

### ISSUE THREAD

**Issue by uhthomas** [romkatv/zsh4humans#198]
Maybe I'm misunderstanding the intended behaviour of SSH teleport but it appears that changes aren't synced when reconnecting?

Assuming an environment where zsh4humans is installed and SSH teleport has previously been used for the target, modify the local `.zshrc` to load a new plugin, like `ohmyzsh/git`:

```zsh
z4h load ohmyzsh/ohmyzsh/plugins/git
```

Reconnect to the target and it appears that nothing has changed, even though the changes work locally.

**Comment by uhthomas** [comment]
Apologies, this was my error. The local zshrc was reset.

**Comment by romkatv** [comment]
A few tips w.r.t. zsh4humans configuration (not related to this issue per se):

1. Since you are using SSH teleportation, you might want to enabled shared command history. See https://github.com/romkatv/zsh4humans/issues/150#issuecomment-966190428.
2. Tip on changing current directory: https://github.com/romkatv/zsh4humans/issues/149#issuecomment-953597823. It also mentions how to bind TAB in all fzf widgets for a large increase in usability.
3. If you haven't yet flipped `recurse-dirs` to `yes`, give it a try. It might get a little bit to getting used to but afterwards you won't be able to live without it. It's a good idea to familiarize yourself with fzf query syntax (`foo$` for suffix, space to search multiple terms, etc.).
4. Flipping `setup no_auto_menu` to `setopt auto_menu` is a good idea.
5. Enabling shell integration may enable extra features (depending on the terminal) and shouldn't have any adverse effects:
  ```zsh
  zstyle ':z4h:' term-shell-integration 'yes'
  ```
6. Flipping `forward-char` to  `accept` will make all cursor movement widgets consistent.
7. You might want to bind `*-zword` widgets that operate on whole shell arguments (e.g., `ls '/foo/bar baz' has two zwords). These widgets are: `z4h-forward-zword`,  `z4h-backward-zword`, `z4h-kill-zword` and `z4h-backward-kill-zword`. There are `word` variants of all these widgets, too.
8. If you are using transient prompt in powerlevel10k (great option by the way), add this to make it work consistently when closing an SSH connection:
  ```zsh
  z4h bindkey z4h-eof Ctrl+D
  setopt ignore_eof
  ```
8. If all hosts you SSH to are listed in `~/.ssh/config` (good idea by the way), add this to improve completions for `ssh` and similar commands:
  ```zsh
  zstyle ':completion:*:ssh:argument-1:'       tag-order          hosts users
  zstyle ':completion:*:scp:argument-rest:'    tag-order          hosts files users
  zstyle ':completion:*:(ssh|scp|rdp):*:hosts' hosts
  ```
9. If your terminal has an option to open a tab in the same directory as another tab, and if that doesn't work with zsh4humans, add this:
  ```zsh
  zstyle ':z4h:' propagate-cwd yes
  ```
10. If you configure your terminal to allow shell to change title (most terminals have this enabled by default), you'll have nice title. You can configure it further: https://github.com/romkatv/zsh4humans/issues/147#issuecomment-950947452
11. If you are using a two-line prompt (great idea if you enable transient prompt) and/or have an empty line before it (ditto), you can make prompt rendering smoother with `POSTEDIT=$'\n\n\e[2A'` or `POSTEDIT=$'\n\e[A'`. The first is for a two-line prompt with an empty line before it (that is, 3 lines total for prompt); the second is for a two-line prompt without an empty line or a one-line prompt with empty line.

**Comment by uhthomas** [comment]
Thanks for the tips! Will some of these options become standard in v6?

5. This works okay but I had to disable the blue triangles (marks) which come with things like iterm2. See https://iterm2.com/documentation-shell-integration.html

**Comment by romkatv** [comment]
> Thanks for the tips! Will some of these options become standard in v6?

Yes.

> 5. This works okay but I had to disable the blue triangles (marks) which come with things like iterm2. See https://iterm2.com/documentation-shell-integration.html

I'm aware. I also find those marks ugly.
