### ISSUE TITLE
glob menu and incorrect completion for some commands

### ISSUE THREAD

**Issue by uhthomas** [romkatv/zsh4humans#199]
This is kind of a two in one as both are related to each other.

I was trying to use `git reset` to unstage a file but completion would only show branches and refuse to list files. In some cases, nothing at all.

```sh
git reset .zs<TAB>
```

So I wanted to use the standard fzf way of using `*` or `**` to list files, but this doesn't show a menu. It just adds all files to the command which isn't what I want or what I expected to happen coming from fzf-tab.

Thanks as always for your help!

**Comment by romkatv** [comment]
> I was trying to use `git reset` to unstage a file

Use `git restore` instead.

If you really want to use `git reset`, you can probably configure its completions through tags. See https://zsh.sourceforge.io/Doc/Release/Completion-System.html.

What I'm trying to say here is that zsh4humans doesn't generate completions, it only presents them. What is generated can be configured via usual means.

> So I wanted to use the standard fzf way of using `*` or `**` to list files

This isn't supported and unlikely to ever be. It's just a hack that fzf uses because it's unable to generate proper completions.

**Comment by uhthomas** [comment]
That makes sense, thanks for the pointer on `git restore`. My new favourite git subcommand right next to `git switch` 😄 

Is there any way to switch between listing commands, directories or even forcing a menu in some contexts? I definitely don't expect zsh4humans, or any zsh config, to support every single command. As such, being unstable to use completion becomes frustrating.

**Comment by romkatv** [comment]
You can do that via the usual zsh means. The system is quite flexible although the learning curve is rather steep. See https://zsh.sourceforge.io/Doc/Release/Completion-System.html
