### ISSUE TITLE
Proper alternative to eval?

### ISSUE THREAD

**Issue by DanMossa** [romkatv/zsh4humans#220]
Hello!

I understand there are no plans for any extensive documentation but i'm curious if there's a proper alternative to `eval`?

An example of this would be me wanting to add another plugin (https://github.com/ajeetdsouza/zoxide). When following the examples under install, I see that I should add `eval "$(zoxide init zsh)"` and 

> For completions to work, the above line must be added after compinit is called. You may have to rebuild your cache by running rm ~/.zcompdump*; compinit.

What the proper way to do this in z4h?

**Comment by romkatv** [comment]
zsh4humans has built-in tools for changing current directory. See https://github.com/romkatv/zsh4humans/blob/master/tips.md#current-directory. Have you tried it?

**Comment by DanMossa** [comment]
@romkatv 

When looking at the issues in the repo, I've always appreciated how you actually try to understand what the end goal is.

I'll 100% take a look at the link you sent me and I'll respond back!

Thanks!

**Comment by DanMossa** [comment]
So the alt+r makes sense and so does cd tab,

But zoxide does exactly what I'm looking for, which is no matter where I am I can get into the folder.

If my old is located in ~/one/two.

I'm in one and then I cd into two.

Later on when I hit alt+r and type two, the first that appears is wrong.

How can I go about using eval correctly?

Thanks!

**Comment by romkatv** [comment]
> Later on when I hit alt+r and type two, the first that appears is wrong.

From the example you've given `~/one/two` is the only directory that matches "two", so it's the only one that is shown. Did you expect something else? Which directory do you want to be offered in this case?

FWIW, if I wanted to change my current directory to `~/one/two`, I would search for `two$`, `/two` or `/two$`. The latter being the most specific. Also keep in mind that you can combine multiple search terms by separating them spaces. So if `/two$` gives too many results, I would hit space and add `/one/`.

> How can I go about using eval correctly?

What happens if you do what zoxide docs tell you to do, and what do you expect to happen instead?

**Comment by DanMossa** [comment]
Oh wait. I completely misunderstood. What you're doing makes perfect sense and it actually works exactly like I want.
I really appreciate you. Thank you!
