### ISSUE TITLE
My initial feedback

### ISSUE THREAD

**Issue by camsteffen** [romkatv/zsh4humans#24]
This is great! Just some minor feedback/questions...

Can't wait to use z4h ssh!

Add a comment to `export XDG_CACHE_HOME` stating that it is optional or why it is needed. I don't currently use these variables (I'm a mac user).

I would like to see `Enable vi key bindings? [y/n]` on install.

Add more content to `z4h help install`: Where does it install to? What happens if it is already installed? Is it intended to be used inside/outside .zshrc or both? How do I use the installed repo (using `z4h source`)? How does it affect `z4h update` and `z4h init`?

Should there be `z4h uninstall`? Or a way to clean the cache?

The start of the p10k wizard feels a little abrupt/unexpected when installing z4h. Maybe the z4h installer should display "Press Enter to run the powerlevel10k configuration wizard". This would bypass the p10k functionality of running config on startup (if I understand correctly).

Can the z4h installer prompts accept input instantly without enter? (like p10k wizard)

Add an install finished message like:

>Zsh for Humans successfully installed.
>
>You may edit ~/.zshrc to make further customizations to zsh. After making changes, run exec zsh to restart zsh.
>
>Zsh for Humans will automatically check for updates once a month. You can change this in ~/.zshrc.

Can you explain this comment in .zshrc for my curiousity? "Code prior to this line should not assume the current shell is Zsh." Why would .zshrc run in a different shell?

If `z4h chsh` is ran outside of .zshrc, this outcome is surprising:

    Won't ask again unless $Z4H/stickycache/no-chsh is deleted.
    Consider removing z4h chsh call from ~/.zshrc.

It should either skip the caching or just fail altogether. Should be documented in `z4h help chsh` if intended for .zshrc only.

A `man z4h` entry might be nice.

**Comment by romkatv** [comment]
> This is great! Just some minor feedback/questions...

Thanks for giving it a try and sharing feedback.

> Add a comment to `export XDG_CACHE_HOME` stating that it is optional or why it is needed. I don't currently use these variables (I'm a mac user).

Cannot think of a comment that would be short and useful. I'm also struggling to imagine an issue that users might open and that could be prevented by placing a comment above `export XDG_CACHE_HOME`.

Any ideas?

> Can you explain this comment in .zshrc for my curiousity? "Code prior to this line should not assume the current shell is Zsh." Why would .zshrc run in a different shell?

You can replicate your zsh4humans shell on another machine by copying `~/.zshrc` and executing it with `sh`. See https://github.com/romkatv/zsh4humans/blob/v2/README.md#replicating-zsh-for-humans-on-another-machine-or-restoring-it-from-a-backup.

This feature may be odd but it costs almost nothing because zsh4humans needs the ability to escape from bad zsh versions anyway.

---

The reamaining suggestions from your feedback are premature at this point. v2 doesn't reflect the end-goal of zsh4humans. I've released what I had because I won't be actively working on the project for some time and because the current state is useful.

**Comment by camsteffen** [comment]
> Cannot think of a comment that would be short and useful.

Maybe this:

```
# Export XDG environment variables before running z4h (optional).
# Other environment variables are exported later.
export XDG_CACHE_HOME="$HOME/.cache"
```

> You can replicate your zsh4humans shell on another machine by copying `~/.zshrc` and executing it with `sh`.

I see. Yes it is odd because it is expanding the scope of how `.zshrc` is used. But it does seem like the most sensible way to accomplish that feature. Perhaps you could expand that comment a bit too. This is a peculiar point that is important for anyone reading the file to understand.

```
# Code prior to this line should not assume the current shell is Zsh
# since this file may be used to setup Zsh on any machine.
# Afterwards we are in Zsh.
. "$Z4H"/z4h.zsh || return
```

Excited to see future developments! It would be nice to see a "Future Goals" section with bullet points on the readme. I guess documentation is my thing. 😆

**Comment by romkatv** [comment]
I'm not generally receptive to suggestions on how my projects can be improved. Nothing personal, it's just how I work.

The most valuable feedback is when users tell me what they personally want. "I want to use vi keymap!" This is valuable. "Installation should ask whether to enable vi or emacs keymap". Meh.

Or when they ask questions because they don't understand something. "Why is it necessary for the top of ~/.zshrc to be written in POSIX shell?" Good question! "You should add a comment with the explanation." Meh.

It also bears repeating that zsh4humans isn't yet at the phase where packaging polish becomes a priority. It'll come later, just not yet. There are still major things that I need to build.

**Comment by camsteffen** [comment]
That's fair.
