### ISSUE TITLE
Is the project dying? How can we contribute to its future? What are possible alternatives?

### ISSUE THREAD

**Issue by MicaelJarniac** [romkatv/zsh4humans#254]
On the very top of README it says something about the project no longer having much support, bugs potentially going unfixed, and no new features in sight.

I wanted to know if the project will no longer be maintained and if there's anything we can do to help. I didn't find options for donating, for example.

I never used z4h, but I had heard about it a while ago, and just now decided to try it out on my new computer.

And if the project is going to be abandoned, what are possible alternatives? z4h seems to be excellent, and it'd be nice to know if there's anything else that gets close.

**Comment by romkatv** [comment]
> On the very top of README it says something about the project no longer having much support, bugs potentially going unfixed, and no new features in sight.

Correct. This is up to date.

> I wanted to know if the project will no longer be maintained [...]

Either you've already answered this yourself or I'm unsure what you are asking.

> [...] and if there's anything we can do to help.

Help to achieve what?

> And if the project is going to be abandoned, what are possible alternatives?

I have no plans to abandon z4h because I'm using it myself. I just cannot afford to spend my time implementing features I don't need or to make everything work perfectly in environments I don't care about (e.g., writing workarounds for bugs in obscure terminals and window managers).

z4h isn't the kind of project that needs active mainteanance to keep working. What I've implemented works and will keep working.

> z4h seems to be excellent

Thank you.

**Comment by MicaelJarniac** [comment]
Thanks a lot for clarifying. I was afraid the project was going to stop working or something like that, but it doesn't seem to be the case then.

> Help to achieve what?

I'm not sure. Many projects accept donations to help compensate for the time and effort of the devs. I was thinking about something along those lines.

**Comment by romkatv** [comment]
Thanks, I really appreciate your trying to help. I do not accept donations though. The thing is, I have a limited amount of time. I wrote z4h because I wanted to have a nice shell environment. Now I do. I'm not keen on spending more time on it for I can spend it more fruitfully elsewhere. Everyone is welcome to use my code, modify it, etc.
