### ISSUE TITLE
ssh and TERM

### ISSUE THREAD

**Issue by tumd** [romkatv/zsh4humans#32]
Hi,

When on a linux desktop, my current terminal emulator usually is [Termite](https://github.com/thestinger/termite) which has it's own [terminfo](https://github.com/thestinger/termite#terminfo) and TERM set to `xterm-termite`.
This can cause some issues when ssh'ing to hosts that doesn't have this terminfo installed, and installing this terminfo on all remote hosts doesn't seem like a good option.
A reasonable solution might be to have this [ssh-function](https://github.com/vincentbernat/zshrc/blob/master/rc/ssh.zsh#L3) locally. 
If your remote host has z4h already installed, the `LC__ORIGINALTERM` environment variable sent from your source host would need to be [evaluated](https://github.com/vincentbernat/zshrc/blob/master/rc/02-terminfo.zsh#L4) early in `z4h.zsh`, setting the TERM to the most suitable value, with reasonable fallbacks.

I tried to implement the above in my own .zshrc after `z4h init`-block, but that seem be to late in the execution. And I'm not sure what issues I may cause myself if I apply the TERM-evaluation code before `z4h.zsh` is loaded.

BTW, have a look at [vincentbernat's zshrc](https://github.com/vincentbernat/zshrc)-repo. Lots of interesting features in there. I've adopted both the [bookmark](https://github.com/vincentbernat/zshrc/blob/master/rc/bookmarks.zsh)-function and the [locale settings](https://github.com/vincentbernat/zshrc/blob/master/rc/01-locale.zsh) from there.

---
Sidenote;
Just wanted to highlight an error occurring for me on a host using latest update of z4h v3;
```
❯ 
-z4h-zle-line-init:zle:4: bad option: -z
thomasd@thomasd-lab  ~
❯ zsh --version
zsh 5.7.1 (x86_64-debian-linux-gnu)
```
(and yes, I should stick to the stable releases :upside_down_face:)

**Comment by romkatv** [comment]
Thanks for the links. It does indeed look very useful at the first glance. I'll go over that code later.

`TERM` fallbacks don't work verify well. If `TERM` is `xterm-kitty` and you fall back to `xterm-256color`, it'll appear to work at first but your terminal will in fact be broken. I'm not sure if `xterm` will work but even if it does, the experience would suck. All machines you connect to must have terminfo designated by your terminal -- all workarounds lead to subtle brokenness.

When z4h starts it checks whether the current shell is good enough. If it isn't, zsh from zsh-bin is installed. The check is hard-coded to the following:

1. Shell must be zsh.
2. `ZSH_VERSION` must be at least 5.4. (I plan to make this configurable so that you can rely on, say, zsh 5.8 in your personal rc files.)

I can add another condition:

3. Must support `$TERM`.

If I do this, you'll get zsh from zsh-bin when you connect to a remote host without "xterm-termite" terminfo. zsh-bin has complete terminfo database, so it'll work.

You can check whether zsh-bin does indeed work by manually installing it on the remote host. See https://github.com/romkatv/zsh-bin#installation.

What do you think?

> Just wanted to highlight an error occurring for me on a host using latest update of z4h v3;

Thanks! Fixed.

**Comment by romkatv** [comment]
Turns out zsh-bin doesn't have terminfo for "xterm-termite" but it does have "termite". I'll need to fix this.

**Comment by tumd** [comment]
Ah. I havn't tested zsh-bin with termite yet. Out of curiosity I was trying to figure out how one would find the terminfo db or some way to list what's included on the current system/shell.

**Comment by romkatv** [comment]
I've been through that rabbit hole and I think I know everything there is to know about terminfo and zsh. zsh-bin is a good solution for this problem, I just need to pack more terminfo definitions there.

By the way, if you update v3, your usage of `z4h ssh` might break. So heads up, I guess. v3 is a massive upgrade over v2 but it's still bleeding edge.

**Comment by maximbaz** [comment]
> I can add another condition:
> 
> Must support $TERM.

Just hit the same, I think your proposal makes a lot of sense 👍

**Comment by romkatv** [comment]
This is done in v3. At an early stage during zsh initialization a check is performed to see whether there is terminfo entry for `$TERM`. If not, and if the current zsh is not from zsh-bin, zsh-bin gets installed. zsh-bin has embedded terminfo database that includes everything from ncurses plus xterm-kitty and termite. If there are terminal emulators for which zsh-bin doesn't have terminfo, please let me know.

**Comment by atwok** [comment]
Hi. I ran into a similar issue with xterm-24bit and xterm-24bits (blame emacs for the one with the 's').   

Here's a description of how to use them for tmux 24-bit : https://github.com/syl20bnr/spacemacs/wiki/Terminal

I've attached the file I run through tic to get the TERM definitions I use for tmux and emacs.  I'm not sure how to get them in the .terminfo format you include with zsh-bin but if you could include these two with it, I think it would be a big help to others as well.

The other option is to explain how to use my own version of zsh which will see these new TERM definitions?  I have zsh via linuxbew but I'm unsure how to get zsh4humans to mine up.  Unfortunately since I'm on a Centos 7 box, the initial zsh version is old and perhaps that's why the included zsh gets used?

I know you've added some linuxbrew support in v5 so maybe this is already taken care of?

[terminfo-24bit.txt](https://github.com/romkatv/zsh4humans/files/6058859/terminfo-24bit.txt)

**Comment by romkatv** [comment]
> Hi. I ran into a similar issue with xterm-24bit and xterm-24bits (blame emacs for the one with the 's').

Do you need both xterm-24bit and xterm-24bits? The link you've posted doesn't mention the latter.

**Comment by atwok** [comment]
I use emacs in terminal mode and it uses xterm-24bits for 24-bit color so for emacs, yes that would be appreciated.  Now maybe it can do that without zsh being aware of it?  I'm not sure how that works.

**Comment by romkatv** [comment]
Emacs sets `TERM=xterm-24bits` in its own terminal, correct? Where is the official terminfo/termcap definition for it?

What's `xterm-24bit`? Which terminal uses it?

**Comment by atwok** [comment]
The official gnu docs define xterm-emacs here:
https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html which I could probably switch to if that's the way you want to support it

But the following is all over the internet:

https://stackoverflow.com/questions/14672875/true-color-24-bit-in-terminal-emacs <= 2nd answer, which is what I sent you

I'm not sure what emacs sets in its own terminal.  I don't use terminals from within emacs because they dont always support everything you want cleanly.

I use xterm-24bit in Window Terminal.  It's supported by any modern terminal that supports 24 bit color AFAIK.

I apologize if I'm not answering your exact question.  I just understand what I do, not necessarily why :(

**Comment by romkatv** [comment]
> https://stackoverflow.com/questions/14672875/true-color-24-bit-in-terminal-emacs <= 2nd answer, which is what I sent you

This says to manually set `TERM=xterm-24bit` when starting emacs. Is this what you do?

I'm trying to figure out why you need both `xterm-24bit` and `xterm-24bits` and if there is a difference between them.

**Comment by atwok** [comment]
Yes, I set TERM on the way into emacs (TERM=xterm-24bit emacs -nw) as well as my $TERM in zsh that way.  Tmux seems happy with that (which I use as well).

AFAIK, the 'bits' one has semicolon seperators and that's the difference.  I believe there are post lamenting the fact that someone defined it both ways but I can't find proof of that at the moment.  I'm not sure anything other than emacs uses the semicolon notation?  Or maybe it doesn't even need it anymore?  I'm not sure.

**Comment by romkatv** [comment]
Do I understand it correctly that you never set `TERM=xterm-24bits` and thus never actually use `xterm-24bits`? Can you verify that deleting `xterm-24bits` has no effect?

**Comment by atwok** [comment]
So based on my alias, I do seem to use:

TERM=xterm-24bits emacs -nw

Is there an easy way to get zsh4humans to use my zsh and not zsh-bin so I can do some of this testing without having to figure out how to rollback to my previous zsh enviroment?

(Thanks again for all your help and patience with this)

**Comment by atwok** [comment]
So rephrased:

In my .zshrc, I have TERM set to xterm-24bit
But when I run emacs in terminal mode, I set TERM to xterm-24bits on the command line when I run it

**Comment by romkatv** [comment]
> In my .zshrc, I have TERM set to xterm-24bit
> But when I run emacs in terminal mode, I set TERM to xterm-24bits on the command line when I run it

What happens if you start emacs normally, without overriding `TERM`?

> Is there an easy way to get zsh4humans to use my zsh

If you install zsh 5.8 with all necessary modules and install terminfo for your `TERM`, zsh4humans won't install its own zsh. It only installs its own zsh when the one you have will fail spectacularly.

If you just want to test a different zsh, use this:

```zsh
/bin/zsh -f
```

**Comment by romkatv** [comment]
zsh4humans doesn't care about login shell. It just looks at `zsh` in your path and if it's unusable, then it cannot use it. If it cannot use `zsh` that you already have, it installs one.

I can add a terminfo definition for xterm-24bit (or whatever) to the version of zsh that zsh4humans installs. This isn't difficult. I'm just trying to understand what the name should be (24bit, 24bits, or both). From your comments I first thought you need both but then it doesn't look like you 24bits. From the links you've posted, it doesn't seem like anyone needs it.

**Comment by atwok** [comment]
https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html
<= emacs less than version 27 need some form of user compiled terminfo.
They call it "xterm-emacs" but it's the same thing I sent.

Another solution I'm fine with is using my own version of zsh via linuxbrew
since i have control over my terminfo with it.  I added it to my path
before calling z4h init in my .zshrc but that didn't seem to make a
difference.  Is there more to it that?  Is there an easy way to get my
linuxbrew version of zsh started before the rest of my .zsh* inits run?
Then z4h would see it for sure.

**Comment by romkatv** [comment]
I've tried to reproduce the issue by following these steps.

1. Install Centos 7.
2. Install emacs.
   ```bash
   yum update -y
   yum install -y emacs
   ```
3. Install zsh4humans/v5.
   ```bash
   sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"
   ```
4. When asked where to install zsh, choose `~/.local`. Do not agree to modify `/etc/shells` or to change login shell.
5. Run `emacs -nw` and type `M-x list-colors-display`. Note that it displays 8 colors.
   ![image](https://user-images.githubusercontent.com/1282067/109612652-ebac4580-7ae4-11eb-9d99-27489bb517c1.png)
6. Add `xterm-emacs` terminfo definition:
   ```zsh
   cat >/tmp/terminfo-custom.src <<\END
   xterm-emacs|xterm with 24-bit direct color mode for Emacs,
     use=xterm-256color,
     setb24=\E[48\:2\:\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&\
        %d\:%p1%{255}%&%dm,
     setf24=\E[38\:2\:\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&\
        %d\:%p1%{255}%&%dm,
   END
   tic -x -o ~/.terminfo /tmp/terminfo-custom.src
   ```
7. Run `TERM=xterm-emacs emacs -nw` and type `M-x list-colors-display`. Note that it displays 256 colors.
   ![image](https://user-images.githubusercontent.com/1282067/109612772-172f3000-7ae5-11eb-80d6-0da2eb29b497.png)

Does anything in here look unexpected to you?

From your comments I've got the idea that you modify `TERM` somewhere in your zsh startup files (perhaps `~/.zshrc`). If this is true, you need to remove that. Once you do, relogin and verify that `typeset -p TERM` in zsh prints something standard (e.g., `xterm-256color` or `tmux-256color` but **not** `xterm-24bit`). At this point zsh should work correctly. Now, to use lots of colors in emacs you can follow https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html (just like I did above).

**Comment by atwok** [comment]
I'll give this a shot and get back to you.  I haven't moved to v5 yet.
I've been using v4.

**Comment by atwok** [comment]
Hi.  Sorry for the delay.

I did as you suggested.  I installed v5.  I removed the setting of TERM
from my .zshrc.  I fixed how I was enabling true colors in my own
.tmux.conf.  I'm able to set TERM on the command line while starting emacs
and it produces the results I expected.

Everything works.  Sorry for bothering you.  Thank you again for you help!

**Comment by romkatv** [comment]
Thanks for the update.
