### ISSUE TITLE
How do I disable/delete some default plugins and add in new ones?

### ISSUE THREAD

**Issue by Xe-no1** [romkatv/zsh4humans#340]
Hello, Is there any possible way to change or alter the default plugins? In my case, I want to disable the pre-installed  `zsh-users/zsh-syntax-highlighting` and replace it with `z-shell/F-Sy-H`, my `.zshrc` is the exact default, stock one that came on install. Thanks in advance!

**Comment by romkatv** [comment]
This isn't supported but with some perseverance you can make it work. I don't recommend it though. If you really care about f-sy-h vs z-sy-h, zsh4humans isn't a good choice.

**Comment by Xe-no1** [comment]
Okay got it, thank you for confirming so I don't keep running around in circles! Will configure my own `.zshrc` without zsh4humans then.

**Comment by Xe-no1** [comment]
Might be a bit unrelated, but what would you reccomend other than zsh4humans that offers similar speed, your own [diy++fysh](https://github.com/romkatv/zsh-bench/blob/master/configs/diy%2B%2Bfsyh/skel/.zshrc)?

**Comment by romkatv** [comment]
You can see in the benchmark that `input_lag_ms` for zsh4humans is about the same as it is for diy++fsyh. In general, zsh4humans is fast across the board. You shouldn't pick it for performance though. It's not something you need to force yourself using because other tools are slow. Use it if you like it, and try something else if you don't. Most tools are fast enough in practice.
