### ISSUE TITLE
Additional startup files, referencing functions, updating v3

### ISSUE THREAD

**Issue by RickCogley** [romkatv/zsh4humans#40]
Hi - a couple of questions if you don't mind; sorry for my newbness. In the readme, I see the recommendation not to create the additional startup files: 

> When you start Zsh, it automatically sources ~/.zshrc -- your personal config that builds on Zsh For Humans. Zsh supports several additional startup files with complex rules governing when each file is sourced. The additional startup files are ~/.zshenv, ~/.zprofile, ~/.zlogin and ~/.zlogout. It is not recommended to create these files.

I have been using `zsh` for a few years now, and have accumulated settings in those based on recommendations on sites for some specific situation or in the notes from a `brew install`, in addition to having some settings / lines added by prezto.

Does the above warning mean, I can/should just re-create everything in `~/.zshrc` like setting the EDITOR env var? I assume considering the timing or sequence that these are loaded with, makes the answer "it depends" but, I am thinking to just comb through, find anything I know is essential, and just start fresh. Would you say it's ok to just chuck all my `EXPORT PATH=$PATH:/path/to/foo` type statements into `~/.zshrc`?

### 2. Lots of functions

I've got a number of functions littering up my `~/.zshrc`. I want to move them to an external file and source them, to keep things compact. Is this the best practice assuming I'm using this project? : 

~~~~~
z4h source $HOME/path/to/my/functions.zsh
~~~~~

### 3. Updating

If I install v3, then will the updater update from v3? This bit from `~/.zshrc` appears to govern the updating, but, does channel `stable` mean v2? 

~~~~~
# 'ask': ask to update; 'no': disable auto-update.
zstyle ':z4h:'                auto-update      ask
# Auto-update this often; has no effect if auto-update is 'no'.
zstyle ':z4h:'                auto-update-days 28
# Stability vs freshness of plugins: stable, testing or dev.
zstyle ':z4h:*'               channel          stable
~~~~~

The readme says there is no update mechanism for `.zshrc` so does that mean updating won't clobber my `~/.zshrc` if I put customizations in there then do an update?

**Comment by romkatv** [comment]
> Hi - a couple of questions if you don't mind; sorry for my newbness. In the readme, I see the recommendation not to create the additional startup files:

v3 documentation hasn't been updated yet. It's still identical to v2 and thus out-of-date. The installer now creates two files: `~/.zshenv` and `~/.zshrc`. It's highly recommended that you keep `~/.zshenv` untouched, avoid creating additional files, and put all your customization in `~/.zshrc`.

> Does the above warning mean, I can/should just re-create everything in `~/.zshrc` like setting the EDITOR env var?

Yes. The stock `~/.zshrc` shows where you should add exports. Here's the relevant section:

```zsh
# Export environment variables.
export EDITOR=nano
export GPG_TTY=$TTY
```

(I'm somewhat surprised you are asking where to put `export EDITOR` given that the config literally has this line. It's likely that I'm misunderstanding your question or missing something.)

> I assume considering the timing or sequence that these are loaded with, makes the answer "it depends"

No, it doesn't depend.

> Would you say it's ok to just chuck all my `EXPORT PATH=$PATH:/path/to/foo` type statements into `~/.zshrc`?

Yes, it's a very good idea. Specifically for `path`, simply follow the template that's already there:

```zsh
# Extend PATH.
path=(~/bin $path)
```

You can also use `export PATH=...` but usually dealing with `path` is more convenient.

> I've got a number of functions littering up my `~/.zshrc`. I want to move them to an external file and source them, to keep things compact. Is this the best practice assuming I'm using this project? :
> 
> ```
> z4h source $HOME/path/to/my/functions.zsh
> ```

This will work.

You can also create directory `~/zsh-functions`, put your functions in there (one function per file) and autoload them. For example, the stock `~/.zshrc` has this function:

```zsh
function md() { [[ $# == 1 ]] && mkdir -p -- "$1" && cd -- "$1" }
```

You could create `~/zsh-functions/md` with the following content:

```zsh
[[ $# == 1 ]] && mkdir -p -- "$1" && cd -- "$1"
```

Then remove `md` from `~/.zshrc` and add the following stanza:

```zsh
fpath+=(~/zsh-functions)
autoload -Uz -- ~/zsh-functions/[^_]*(.)
```

The vast majority of functions I've seen that zsh users define can actually be scripts instead. In general, if you can implement something as a script, it's almost always preferable to implement it as a script instead of a function. Drop all your scripts in `~/bin`, add `~/bin` to `path` and you are good to go. Note that `md` cannot be a script because it changes the current directory of the shell (that's why I put it as an example of a user-defined function in `~/.zshrc`).

> If I install v3, then will the updater update from v3?

Yes.

> does channel `stable` mean v2?

No.

Channels are specified for external dependencies (powerlevel10k, zsh-syntax-highlighting, etc.). There is no channel for the core code of zsh4humans.

> The readme says there is no update mechanism for `.zshrc` so does that mean updating won't clobber my `~/.zshrc` if I put customizations in there then do an update?

Correct. You own all your config files. z4h stores its own files in `$Z4H`. You can delete this directory and it'll be recreated. When you run `z4h update`, it only updates files in `$Z4H`. You shouldn't modify anything under `$Z4H`.

The installer doesn't do much. It backs up your existing zsh startup files if you have them, and then downloads `~/.zshenv` an `~/.zshrc`. That's it. These two files are your Zsh config now. Modify them as you like, back them up somewhere, copy them to other machines, etc. When you start zsh, additional files get downloaded to `$Z4H` if they don't exist yet.

**Comment by RickCogley** [comment]
Hi @romkatv, thanks for the detailed answer. I really appreciate the clarity. It's really confusing reading all kinds of different info on zsh rc files; at least for me it was. 

> You can also use export PATH=... but usually dealing with path is more convenient.

Ok, I'll read more about `path`. 

> You could create ~/zsh-functions/md with the following content... 
> The vast majority of functions I've seen that zsh users define can actually be scripts instead. In general, if you can implement something as a script, it's almost always preferable to implement it as a script instead of a function. Drop all your scripts in ~/bin...

Right, thank you; that makes sense. Lately I was starting to re-implement certain functions as scripts. I'll have to read up more on "when a function is preferred or needed". 

> Channels are specified for external dependencies... 

Well noted about this and the updating.

Thanks very much indeed. You obviously know this very well and I am grateful for the advice.

**Comment by romkatv** [comment]
> Hi @romkatv, thanks for the detailed answer. I really appreciate the clarity. It's really confusing reading all kinds of different info on zsh rc files; at least for me it was.
> 
> > You can also use export PATH=... but usually dealing with path is more convenient.
> 
> Ok, I'll read more about `path`.

`path` is an array. It contains the same elements as `PATH`. Changing one parameter automatically changes the other. Dealing with arrays is easier than with colon-separated scalars. That said, you can keep using `PATH` if you like.

Similarly, I noticed that you use `$HOME` instead of `~`. This is fine, even though `~` is easier to work with (it's shorter and cannot be `unset` or changed by user code).

> Right, thank you; that makes sense. Lately I was starting to re-implement certain functions as scripts. I'll have to read up more on "when a function is preferred or needed".

A good rule of thumb is to implement everything as a script if it can be implemented as a script. There are exceptions but not many.

> Thanks very much indeed. You obviously know this very well and I am grateful for the advice.

You are very welcome. Closing the issue as all questions seem to have been answered satisfactorily.
