### ISSUE TITLE
Cursor position when pressing up arrow

### ISSUE THREAD

**Issue by Thiago4532** [romkatv/zsh4humans#53]
Probably this is intentional but I wanna know if it's possible to force cursor position to go to the end of the line when searching in the history.

**Comment by romkatv** [comment]
See https://github.com/romkatv/zsh4humans/blob/d1701984e1c12ccef6224c1413a7ff942e2ef6d0/.zshrc#L52

**Comment by romkatv** [comment]
Note that <kbd>Up</kbd> doesn't simply fetch the last command from history. Instead, it fetches the last command that has the same prefix as what you have before the cursor.

When you set the value of `leave-cursor` to `false`, <kbd>Up</kbd> moves the cursor to the end instead of keeping its position unchanged. This has some unintuitive consequences as it effectively introduces two cursors. One cursor is visible, and it's positioned at the end. The other cursor is invisible and it's positioned at the same place where it was before you pressed <kbd>Up</kbd>. The invisible cursor demarcates the command prefix used by the widget in case you press <kbd>Up</kbd> again. Here's an example of how it usually works.

- Type `cd ` and press <kbd>Up</kbd>. You'll see the last command from your history that starts with `cd `. Let's say it's `cd ~/foo`.
- Now you have a visible cursor at the end and an invisible cursor after `cd `.
- Press <kbd>Up</kbd> again. You'll see the one before last command from your history that starts with `cd `. Perhaps `cd /bar`.

The last point is tricky because it requires you to remember where the invisible cursor is. Many actions lead to the invisible cursor changing its position to align with the visible cursor, so this can be tricky. E.g., if after the first <kbd>Up</kbd> you were to manually move cursor to the left and then back (by pressing <kbd>Left</kbd> followed by <kbd>Right</kbd>), the next <kbd>Up</kbd> wouldn't give you `cd /bar`. Instead, it would give you a command that starts with `cd ~/foo`. This is because the invisible cursor is now positions at the very end.

With `leave-cursor` set to `true` (the default value in zsh4humans) there is always one cursor position. Or, to put it another way, the invisible cursor is always at the same position as the visible. This is achieved by not changing the cursor position when you press <kbd>Up</kbd>. This makes it much easier to reason about <kbd>Up</kbd>. This key always gives you a command that has the same prefix as the current command line up to the cursor. Try typing `cd` and press <kbd>Up</kbd> a few times. You'll cycle through all commands in history that start with `cd`. Crucially, every time you press <kbd>Up</kbd>, it's clear which prefix is used for searching history -- it's always the portion of the command line left of cursor.

**Comment by romkatv** [comment]
Closing because the reporter has vanished.
