### ISSUE TITLE
Beep on selecting the previous item in history

### ISSUE THREAD

**Issue by anstadnik** [romkatv/zsh4humans#54]
The title says it. Since that's a common action, it distracts a lot.
I've done a quick search and found [this ](https://blog.vghaisas.com/zsh-beep-sound/) article. If I run `unsetopt beep`, it fixes the issue, but I don't mind beeping in other situations. `unsetopt histbeep` and `unsetopt listbeep` didn't fix the issue. I assume that there might be something else going on when selecting the previous item since the problem does not occur with the clean zsh setup.
To represent the issue, simply running the example docker would be enough.

**Comment by romkatv** [comment]
> To represent the issue, simply running the example docker would be enough.

Could you copy-paste the docker command here?

Is it enough to simply execute the command to get a beep? If not, what do I need to do after running the docker command to get a beep?

**Comment by romkatv** [comment]
Closing because there is no enough info to reproduce the problem.

**Comment by anstadnik** [comment]
Sorry for the late reply.
The command is 

```
docker run -e TERM -e COLORTERM -w /root -it --rm alpine sh -uec '
  sh -c "$(wget -O- https://raw.githubusercontent.com/romkatv/zsh4humans/v2/install)"'
```
To get a beep, run the command, and press Ctrl+p to select the previous command. Even though there is no previous command, it will beep. Alternatively, you can type something like `ls`, and after press Ctrl+p to select it, and it will be followed by a beep.
Please tell me if you need me to provide you more info about my setup etc.

**Comment by romkatv** [comment]
Thanks for the additional info. I've reproduce this in zsh4humans v2 (the version you are using) but not in zsh4humans v4 (the latest version) [1]. I'm fixing only serious bugs in v2 and I'm afraid this one won't qualify. You have a few options:

1. Upgrade to v4. Since v4 is not backward compatible with v2, there is no automatic migration path. You'll need to [install v4](https://github.com/romkatv/zsh4humans/tree/v4#installation) and then manually transfer some of your customizations to the new `~/.zshrc`. v4 is much better than v2, so it'll probably be worth your time to upgrade.
2. Send a PR against v2 that fixes the issue.
3. Disable beep completely with `unsetopt beep`.

[1] In v4 `beep` is unset by default but even if you manually set it, <kbd>Up</kbd> won't beep.

**Comment by anstadnik** [comment]
Sure! When this issue was created, v2 was the main version (the version which was downloading when following the README.md from the master branch). I'm moving to v4 now.
Thank you!
