### ISSUE TITLE
Question: why not use the zsh/terminfo module for key escape sequences?

### ISSUE THREAD

**Issue by infokiller** [romkatv/zsh4humans#7]
Hey!

I'm wondering why you're directly using escape codes instead of using the `zsh/terminfo` module.
For example, you're using this:
```zsh 
bindkey '^[[H' beginning-of-line
```

Instead of:
```zsh 
bindkey "${terminfo[khome]}" beginning-of-line
```

Thanks!

**Comment by romkatv** [comment]
Home key can send (at least) 3 different codes on a single system I use -- Linux.

1. In xterm-compatible terminal in raw mode: `^[[H`.
2. In xterm-compatible terminal in application mode: `^[OH`.
3. In TTY: `^[[1~`.

If you try using plain `bindkey "${terminfo[khome]}" beginning-of-line`, you'll notice that it doesn't work. This is because `$terminfo[khome]` gives escape codes for application mode for terminals that support it. This isn't the default terminal mode though -- the default is raw. So to make use of `$terminfo[khome]` you would have to put terminal in application mode. If you do so, many command line apps that handle arrow keys will break because they expect raw mode. So you could add extra code that switches terminal to raw mode in preexec and back to application mode in `zle-line-init`. This is quite a bit of complexity and it still fails in some cases. For example, if you call something from a zle widget, that *something* will get terminal in application mode and may break because of it. Lastly, using ${terminfo[khome]}` doesn't mean you can get rid of all escape code specifications. You still have to write them by hand for things like `alt-left` and many others. So using `${terminfo[khome]}` is just adding extra complexity to your config and making it more brittle.

**Comment by infokiller** [comment]
Thanks for the detailed answer!
I'm a bit confused about terminal modes. This is my current understanding: 

Most/all terminals have the following modes:

- raw mode: all keypresses are directly transmitted to the program 
- cooked mode: some preprocessing is done by the terminal before sending the bytestream to the program. For example, pressing <kbd>Backspace</kbd> (where the terminal deletes the last char without involving the program) or <kbd>Ctrl-C</kbd> (where the program receives a signal directly).

Actually, it's possible to use intermediate modes as well, since terminals support fine grained configuration of this behavior. For example, you can have <kbd>Ctrl-C</kbd> send a signal to the program, but still send <kbd>Backspace</kbd> to the program. This can be done by tweaking terminal settings mentioned in `man stty`.

Now, what is actually application mode? I can see it referenced in the [xterm docs](https://invisible-island.net/xterm/xterm.faq.html#xterm_arrows), along with references to the terminfo `smkx` and `rmkx` capabilities. My understanding from reading it is that it controls the escape codes for "keypad buttons", which will normally include Home, End, PageUp, PageDown, and Arrow keys (and numeric keypad as well?).
That doc indeed mentions that terminfo entries are only valid in application mode.

Is my understanding correct? If so, I understand your motivation, and indeed it makes more sense than the oh-my-zsh approach of using `echoti smkx` in `zle-line-init`.

**Comment by romkatv** [comment]
That's right. Your understanding is correct.

**Comment by infokiller** [comment]
BTW, by TTY do you refer to the Linux virtual console (i.e. <kbd>Ctrl+Alt+[0-9]</kbd> in X11)?
And if you intend to use the escape codes for more terminals, should you check `$TERM` to only use escape codes that are valid for that terminal?

**Comment by romkatv** [comment]
> BTW, by TTY do you refer to the Linux virtual console (i.e. Ctrl+Alt+[0-9] in X11)?

Yes.

> And if you intend to use the escape codes for more terminals, should you check `$TERM` to only use escape codes that are valid for that terminal?

This would be necessary if there were clashes. This simple config doesn't have any, so it can get away with unconditional bindings.

FWIW, I'm working on the second iteration of z4h that has supporting library code outside of zshrc. This gives me access to much higher levels of complexity, so I can provide better API for bindings. Like this:

```zsh
z4h bindkey beginning-of-line emacs,viins home ctrl-a
```

**Comment by infokiller** [comment]
Sounds good, looking forward to the second version.
If this is too early for feedback, let me know and I'll wait before opening issues :)

**Comment by romkatv** [comment]
> If this is too early for feedback, let me know and I'll wait before opening issues :)

Feedback, especially as high quality as yours, is always welcome.
