### ISSUE TITLE
Rehash when new program are installed

### ISSUE THREAD

**Issue by cgestes** [romkatv/zsh4humans#79]
Hi,

is there a way for rehash to be called when new program are installed?

Thanks :)

**Comment by romkatv** [comment]
You can invoke `rehash`.

I suppose this isn't what you have in mind. Please provide more details about what you are trying to do.

**Comment by cgestes** [comment]
Can it be automatic? :D

Without the user needing to call rehash.

**Comment by romkatv** [comment]
> Please provide more details about what you are trying to do.

Pretty please ☝️ Why do you think you want `rehash`? What currently doesn't work the way you want? Please describe what you do, what happens and what you want to happen instead.

> Can it be automatic?

You can call `rehash` automatically on events of your own choosing. E.g., if you want it to be called before every command:

```zsh
function rehash() { builtin rehash "$@"; }
precmd_functions+=(rehash)
```

This doesn't happen by default because rehash can be slow and it's also destructive (it removes manually hashed commands). 

Please answer the questions I've asked above.

**Comment by cgestes** [comment]
Oh sorry. I would like completion of command names to work after installing
something new without having to do anything manual.

Eg:
```
$ pacman -S saucisson

#the command bellow fail to find saucisson
$ sauci<tab>

$ rehash

# this one find saucisson, in the meantime I was sad, I thought I lost my
saucisson
$ sauci<tab>
```

:D

**Comment by romkatv** [comment]
Thanks for the explanation. The standard solution that pretty much everyone employs is to either invoke rehash or manually type the command name once (it’ll be hashed once you invoke it). If you install programs many times in each shell session, then it would make sense to invoke rehash from precmd as I described above.

Is this satisfactorily?

**Comment by cgestes** [comment]
Yeah, that's what I would like to avoid... I know no easy way. :/

**Comment by romkatv** [comment]
I think we are on the same page. See above for how to avoid to manually type `rehash`.
