### ISSUE TITLE
Question: does using `zcompile` actually improve performance?

### ISSUE THREAD

**Issue by infokiller** [romkatv/zsh4humans#8]
I once experimented with using `zcompile` to source scripts (mostly plugins), but my tests didn't show any improvement (at least not significant enough to be visible in benchmarking with tens of runs).
I tried to do the same with the zsh4humans `.zshrc` to see if I get similar results, and indeed I don't see a real improvement. To benchmark, I used two variations:

1. Simple for loop like:
```zsh
for i in $(seq 1 10); do time zsh -i -c exit; done;
```

2. Using [hyperfine](https://github.com/sharkdp/hyperfine):
```zsh 
hyperfine --warmup 1 'zsh -i -c exit'
```

I compared between the current `.zshrc` from master, and a slight variation to source the script directly by adding the following lines:
```zsh 
[[ -f "$2.zwc" ]] && rm "$2.zwc"
source "$2"
```

To this piece of code just above the `if`: https://github.com/romkatv/zsh4humans/blob/ed3ac2b25829865ca702ba088df06f59062e15f9/.zshrc#L18-L20

**Comment by romkatv** [comment]
> does using `zcompile` actually improve performance?

Yes, but very little.

When I was benchmarking zcompile for powerlevel10k startup, the effect size was around 2ms. Powerelvel10k amounts to >70% of zsh code sourced by zsh4humans, and it's already compiled by powerlevel10k itself, so zcompile in zsh4humans has virtually no visible effect.

I kept it there for two reasons. The first is that it'll help a little bit if you source more plugins. However my main goal was to curtail arguments that some plugin manager can do the same job faster. It's much easier for users to understand a simple claim that no plugin manager can achieve faster zsh startup compared to zsh4humans. The alternative statement -- some plugin managers can do it a bit faster but you won't notice it -- is too subtle to understand the implications of.

> `zsh -i -c exit`

While timing this command can tell you *something*, note that it's not the right metric to optimize for if you want to get fast zsh startup. Some snake oil peddlers might try to convince you otherwise but it's easy to show that the timing of `zsh -i -c exit` can be 10 times lower or 10 times higher than the real latency that you care about.

**Comment by infokiller** [comment]
Thanks for the explanation, makes sense.
FWIW, I'm happy that there's no plugin manager in z4h, because I personally haven't seen any benefit in using one, especially when using p10k instant prompt and zsh-defer.

**Comment by romkatv** [comment]
> [...] especially when using p10k instant prompt and zsh-defer.

If you are using p10k instant prompt, zsh-defer will almost always bring more harm than good. What do you use it for?

**Comment by infokiller** [comment]
I use it source a few scripts (but not any plugins). Here's a commented simplified snippet:

```zsh
# Sets DISPALY for wsl1 and wsl2
zsh-defer source wsl.sh
# Sets the terminal title to the running command and does `stty -ixon`
zsh-defer -1 -2 source terminal_settings.sh
# Sets `$GPG_TTY` and `$SSH_AUTH_SOCK`
zsh-defer -1 -2 source auth_agents.sh
# Initializes direnv
zsh-defer -1 -2 eval "$(direnv hook "${SHELL}")"
```

Would you recommend I stop using zsh-defer in those places?

**Comment by romkatv** [comment]
> Would you recommend I stop using zsh-defer in those places?

Yes, absolutely.

My high-level advice is to only add extra stuff to your configuration if it actually helps. Does `zsh-defer` do anything useful that you can detect? By that I don't mean the timing of `zsh -ic ''` (which is meaningless) but something you can detect with your own human senses.

While `zsh-defer` is not doing anything good in your config, it's doing quite a bit of harm. For example, if you type fast enough to keep zle busy, you'll execute command(s) without environment from direnv. When you do get environment from direnv, the message saying so may be missing entirely. (Flags `-1 and -2` don't help because zle cannot print to console willy-nilly.)

Note that zsh-defer for direnv in your config is applied only to `eval` but not to the call to `direnv hook`, which takes 99.9% of direnv initialization time. So it's not even reducing the irrelevant metric of `zsh -ic ''`.

There are similar issues with everything else that's deferred in your config. I suppose setting `DISPLAY` isn't an optional thing and you probably want it to be done before you start executing commands? It shouldn't be deferred then.

A few tips:

1. Use `direnv hook zsh` instead of `direnv hook $SHELL`. If `$SHELL` is `zsh`, you are lucky. If your login shell happens to be `bash`, `direnv hook $SHELL` will result in errors as you'll try to initialize direnv using its integration code for bash.
2. Make sure to use `$TTY` instead of `$(tty)` when initializing `GPG_TTY`. It's 1000+ times faster and doesn't break when using instant prompt.
3. Are you sure you want `stty -ixon` and not `setopt no_flow_control`? If you do the latter, `ctrl-s` and `ctrl-q` won't do anything in zle and can be bound to anything you like. At the same time you retain the ability to pause terminal output with `ctrl-s` when some program starts spewing out logs with the speed of light (resume with `ctrl-q`). If you run `stty -ixon`, the effect on zle is the same but you lose the ability to pause/resume terminal output.

**Comment by infokiller** [comment]
Many thanks for the detailed answer and tips! as always it's really useful.
> > Would you recommend I stop using zsh-defer in those places?
> 
> Yes, absolutely.
Alright, will remove it then.
> 
> My high-level advice is to only add extra stuff to your configuration if it actually helps. Does `zsh-defer` do anything useful that you can detect? By that I don't mean the timing of `zsh -ic ''` (which is meaningless) but something you can detect with your own human senses.
> 
> While `zsh-defer` is not doing anything good in your config, it's doing quite a bit of harm. For example, if you type fast enough to keep zle busy, you'll execute command(s) without environment from direnv. When you do get environment from direnv, the message saying so may be missing entirely. (Flags `-1 and -2` don't help because zle cannot print to console willy-nilly.)
> 
> Note that zsh-defer for direnv in your config is applied only to `eval` but not to the call to `direnv hook`, which takes 99.9% of direnv initialization time. So it's not even reducing the irrelevant metric of `zsh -ic ''`.
Yup, you're right of course, I guess it should have been all inside single quotes...
> 
> There are similar issues with everything else that's deferred in your config. I suppose setting `DISPLAY` isn't an optional thing and you probably want it to be done before you start executing commands? It shouldn't be deferred then.
`$DISPLAY` is not super critical, it's mainly there for clipboard integration (your overall point still stands though).
> 
> A few tips:
> 
> 1. Use `direnv hook zsh` instead of `direnv hook $SHELL`. If `$SHELL` is `zsh`, you are lucky. If your login shell happens to be `bash`, `direnv hook $SHELL` will result in errors as you'll try to initialize direnv using its integration code for bash.
Makes sense
> 2. Make sure to use `$TTY` instead of `$(tty)` when initializing `GPG_TTY`. It's 1000+ times faster and doesn't break when using instant prompt.
Makes sense
> 3. Are you sure you want `stty -ixon` and not `setopt no_flow_control`? If you do the latter, `ctrl-s` and `ctrl-q` won't do anything in zle and can be bound to anything you like. At the same time you retain the ability to pause terminal output with `ctrl-s` when some program starts spewing out logs with the speed of light (resume with `ctrl-q`). If you run `stty -ixon`, the effect on zle is the same but you lose the ability to pause/resume terminal output.
Indeed, I should probably only use `setopt no_flow_control`. Right now both are set in my config. The reason I originally set `stty -ixon` was that the `terminal_settings.sh` script I source (which invokes `stty`) is shared between bash and zsh, and in bash using `stty -ixon` was the only way I found to disable flow control.
Just curious: do you actually ever use <kbd>Ctrl-s</kbd> to pause terminal output?

**Comment by romkatv** [comment]
> Just curious: do you actually ever use Ctrl-s to pause terminal output?

Yes. Let's say I'm running a build or install script for something or other. It prints a ton of stuff to console and runs for quite a while. Is it printing the same error over and over again? Is it stuck in a loop? Should I Ctrl-C it and see what it says or wait a bit longer hoping that it'll finally terminate? Ctrl-S/Ctrl-Q provide a better option.

**Comment by infokiller** [comment]
Got it. I guess I never run into this problem in practice because I always run inside tmux, which provides a copy mode where output is halted. So I just switch to copy mode in those cases.

**Comment by romkatv** [comment]
That sounds cool. I've now 1001 reasons to start using tmux :laughing:

**Comment by infokiller** [comment]
Yup, tmux is really nice for organizing lots of persistent terminal sessions, and it especially shines when SSHing to remote servers, because then even if there's a disconnection, when you connect again you get back the exact terminal state (including previous command output etc.).
And if we're getting into terminal setups and Unix porn, here's a couple of other recommendations: 
- [kitty](https://github.com/kovidgoyal/kitty) is a great terminal emulator. Looking at your public dotfiles I see you tried alacritty, but from my experience kitty is much better (also GPU accelerated) and the author is much more responsive.
- I don't know if you often run commands in multiple machines, but I do and I find it really helpful to be able to search the history from all machines. I use a custom tool in I built for that in golang which is also integrated with fzf but has some improvements like support for multiline commands, storing alias expansions (so if you change aliases in the future you can still search your history with the real commands), ipython integration, syntax highlighted command previews, and showing the context of the command (commands executed before/after). I haven't published it yet (wanted to polish it more before doing so), but I can share it with you if you're interested. There's also [zsh-histdb](https://github.com/larkery/zsh-histdb) which looks good, but I haven't tested it.

**Comment by romkatv** [comment]
I've tried pretty much all terminals out there (had to, due to people filing bugs). Alacritty is a massive disappointment -- no features to speak of and slower than almost everything else, despite their claims. Kitty is decent -- only slightly buggier than VTE-based terminals and not slow. VTE-based terminal (e.g., GNOME Terminal or Tilix) are the best IMO. The least buggy and with the smoothest rendering. If you try GNOME Terminal or Tilix and forget the hype that Kitty enjoys, you'll likely notice that rendering is more pleasant. It's especially noticeable when you enable instant prompt in p10k. I wasn't able to detect any difference in performance between Kitty and VTE in applications I care about, neither subjectively nor with benchmarks. The difference in rendering smoothness when using p10k is noticeable with naked eyes.

That said, Kitty is alright. It's better than most terminals.

As for history, I write history to a separate file on every machine and commit all these files to a private git repo. All these files are available on every machine, so I have a shared history everywhere.

The features of zsh-histdb you describe sound pretty cool and might make it popular if you release it. It seems like your workflow is quite different from mine though. I use few aliases and almost never create or change them, so many features that are important to you aren't important to me. I much prefer to use history to recall often-used commands than to define an alias. FWIW, I also have syntax highlighting in history.

**Comment by infokiller** [comment]
> I've tried pretty much all terminals out there (had to, due to people filing bugs). Alacritty is a massive disappointment -- no features to speak of and slower than almost everything else, despite their claims. 

That's exactly my experience.

> Kitty is decent -- only slightly buggier than VTE-based terminals and not slow. VTE-based terminal (e.g., GNOME Terminal or Tilix) are the best IMO. The least buggy and with the smoothest rendering. If you try GNOME Terminal or Tilix and forget the hype that Kitty enjoys, you'll likely notice that rendering is more pleasant. It's especially noticeable when you enable instant prompt in p10k. I wasn't able to detect any difference in performance between Kitty and VTE in applications I care about, neither subjectively nor with benchmarks. The difference in rendering smoothness when using p10k is noticeable with naked eyes.
> 
> That said, Kitty is alright. It's better than most terminals.

Before Kitty I used Termite which is based on VTE. I don't know about p10k instant prompt, but at least when doing fast scrollback and some vim editing Kitty felt smoother and more responsive to me. I guess I'll give Gnome Terminal a try to see if it's any different.
> 
> As for history, I write history to a separate file on every machine and commit all these files to a private git repo. All these files are available on every machine, so I have a shared history everywhere.
> 

Does zsh "natively" support fetching history entries from multiple files?
If so, how does sorting/matching work with fzf?

> The features of zsh-histdb you describe sound pretty cool and might make it popular if you release it. It seems like your workflow is quite different from mine though. I use few aliases and almost never create or change them, so many features that are important to you aren't important to me. I much prefer to use history to recall often-used commands than to define an alias. FWIW, I also have syntax highlighting in history.

I guess it's a typo, but I just want to clarify that zsh-histdb is not my project, it's an alternative one which looks good from a quick look.
I also don't define a ton of aliases nor change them often, but I do use them often. Expending them mainly helps with searching and correctly computing stats (how often do I type `git`?).

**Comment by romkatv** [comment]
> Does zsh "natively" support fetching history entries from multiple files?

Yes. You can load anything into active history with `fc -RI`.

> If so, how does sorting/matching work with fzf?

You can define any matching you like. I do it like this: first match history from my current machine, then from other machines. You can even create multiple modes: strictly by timestamp across all machines; my machine first then by timestamps, etc.

**Comment by infokiller** [comment]
> > Would you recommend I stop using zsh-defer in those places?
> 
> Yes, absolutely.
> 
> My high-level advice is to only add extra stuff to your configuration if it actually helps. Does `zsh-defer` do anything useful that you can detect? By that I don't mean the timing of `zsh -ic ''` (which is meaningless) but something you can detect with your own human senses.
> 
> While `zsh-defer` is not doing anything good in your config, it's doing quite a bit of harm. For example, if you type fast enough to keep zle busy, you'll execute command(s) without environment from direnv. When you do get environment from direnv, the message saying so may be missing entirely. (Flags `-1 and -2` don't help because zle cannot print to console willy-nilly.)
> 
> Note that zsh-defer for direnv in your config is applied only to `eval` but not to the call to `direnv hook`, which takes 99.9% of direnv initialization time. So it's not even reducing the irrelevant metric of `zsh -ic ''`.
> 
> There are similar issues with everything else that's deferred in your config. I suppose setting `DISPLAY` isn't an optional thing and you probably want it to be done before you start executing commands? It shouldn't be deferred then.
> 
> A few tips:
> 
> 1. Use `direnv hook zsh` instead of `direnv hook $SHELL`. If `$SHELL` is `zsh`, you are lucky. If your login shell happens to be `bash`, `direnv hook $SHELL` will result in errors as you'll try to initialize direnv using its integration code for bash.
> 2. Make sure to use `$TTY` instead of `$(tty)` when initializing `GPG_TTY`. It's 1000+ times faster and doesn't break when using instant prompt.
> 3. Are you sure you want `stty -ixon` and not `setopt no_flow_control`? If you do the latter, `ctrl-s` and `ctrl-q` won't do anything in zle and can be bound to anything you like. At the same time you retain the ability to pause terminal output with `ctrl-s` when some program starts spewing out logs with the speed of light (resume with `ctrl-q`). If you run `stty -ixon`, the effect on zle is the same but you lose the ability to pause/resume terminal output.

I tried to remove zsh-defer in those places and I ran into one issue: direnv may write to stdout which makes instant prompt unhappy.
What would you suggest in this case?

**Comment by romkatv** [comment]
> I tried to remove zsh-defer in those places and I ran into one issue: direnv may write to stdout which makes instant prompt unhappy.

On the plus side, it confirms that previously direnv was either not initialized on the first prompt or its output was silently suppressed.

> What would you suggest in this case?

There are several things you can try. One is to set `POWERLEVEL9K_INSTANT_PROMPT=quiet`. Since you understand how instant prompt affects initialization, there is no point in using verbose mode. Note that `quiet` doesn't suppress console output, it just removes the warning that accompanies it.

In addition, you can change the direnv hook so that it doesn't produce output on success. Powerlevel10k prompt tells you when direnv is active, so "loading" and "unloading" messages from direnv have low utility. This should do it:

```zsh
_direnv_hook() {
  emulate -L zsh -o no_multi_os
  local msg
  {
    local err
    err=$(direnv export zsh 2>&1 1>&3) || print -r -- $err >&2
  } 3>&1 | {
    local out
    IFS= read -rd $'\0' out
    emulate zsh -c "$out"
  }
}
add-zsh-hook precmd _direnv_hook
```

You can also replace `precmd` with `chpwd`. It'll speed up prompt but will require you to type `cd .` after creating or deleting `.envrc` in the current directory. Given how rarely you create these files, it can be a good compromise. (Note that direnv doesn't reload `.envrc` when you change its content even when you run the hook from precmd.)

**Comment by infokiller** [comment]
> > I tried to remove zsh-defer in those places and I ran into one issue: direnv may write to stdout which makes instant prompt unhappy.
> 
> On the plus side, it confirms that previously direnv was either not initialized on the first prompt or its output was silently suppressed.
> 

With `zsh-defer -1 -2` it does initialize and some of the output is shown (specifically "direnv: loading .envrc" is always shown, but the actual command is sometimes suppressed)

> > What would you suggest in this case?
> 
> There are several things you can try. One is to set `POWERLEVEL9K_INSTANT_PROMPT=quiet`. Since you understand how instant prompt affects initialization, there is no point in using verbose mode. Note that `quiet` doesn't suppress console output, it just removes the warning that accompanies it.

I wanted to do that, but then saw the warning "Zsh will start quickly but prompt will jump down after initialization." so thought it may not be a good idea.
> 
> In addition, you can change the direnv hook so that it doesn't produce output on success. Powerlevel10k prompt tells you when direnv is active, so "loading" and "unloading" messages from direnv have low utility. This should do it:
> 
> ```shell
> _direnv_hook() {
>   emulate -L zsh
>   local msg
>   {
>     local err
>     err=$(direnv export zsh 2>&1 1>&3) || print -r -- $err >&2
>   } 3>&1 | {
>     local out
>     IFS= read -rd $'\0' out
>     eval $out
>   }
> }
> add-zsh-hook precmd _direnv_hook
> ```
> 
> You can also replace `precmd` with `chpwd`. It'll speed up prompt but will require you to type `cd .` after creating, deleting or modifying `.envrc` in the current directory. Given how rarely you do these things, it can be a good compromise.
> 
> Edit: Simplified the hook and fixed the last paragraph.

This should be better, right?

**Comment by romkatv** [comment]
> I wanted to do that, but then saw the warning "Zsh will start quickly but prompt will jump down after initialization." so thought it may not be a good idea.

It's unusual for output to appear *above* prompt while you are typing, forcing prompt to jump down. The warning you've quoted says as much.

If you understand what it means by "prompt will jump down after initialization", you can make your own call whether it's OK or not.

Regardless of what you decide to do with direnv, you should probably set `POWERLEVEL9K_INSTANT_PROMPT=quiet` as it will only suppress the warning that you already understand. You can simply reproduce the warning in your head every time you see output above prompt when starting zsh. It's not like the warning will disappear and you will have no indication of output. The warning only appears when *there is* output, and it effectively says "hey, look, output!".

> This should be better, right?

To me this seems better as I don't find "loaded/unloaded" messages useful. I'd suppress them even if I weren't using instant prompt.

**Comment by infokiller** [comment]
Thanks, SG.
There's an issue with the `_direnv_hook` function above: when I test it by having an `.envrc` file with `cat no-such-file`, no output is shown.
I'm trying to debug this now.

**Comment by infokiller** [comment]
Thanks, SG.
There's an issue with the `_direnv_hook` function above: when I test it by having an `.envrc` file with `cat no-such-file`, no output is shown.
The issue seems to be that `direnv export zsh` doesn't fail even if the commands in `.envrc` fail.

**Comment by infokiller** [comment]
I think for now I'll just set `POWERLEVEL9K_INSTANT_PROMPT=quiet` as you suggested keep the normal direnv hook. I can live with the prompt jumping a bit :)
Thanks a lot!

**Comment by romkatv** [comment]
If some of the messages printed by direnv on success are useful to you, don't suppress stdout. You can either live with messages occasionally printed above instant prompt, or initialize direnv above instant prompt preamble. I think it's not terribly slow. Basically, add this at the top of zshrc:

```zsh
emulate zsh -c "$(direnv export zsh)"
```

You can leave the simple form of direnv initialization below the instant prompt preamble:

```zsh
emulate zsh -c "$(direnv hook zsh)"
```

**Comment by romkatv** [comment]
> If some of the messages printed by direnv on success are useful to you, don't suppress stdout. You can either live with messages occasionally printed above instant prompt, or initialize direnv above instant prompt preamble. I think it's not terribly slow. Basically, add this at the top of zshrc:
> 
> ```shell
> emulate zsh -c "$(direnv export zsh)"
> ```

I think instant prompt should even be able to display direnv indicator if you do this.

**Comment by infokiller** [comment]
Just tested it on 1-2 dirs: works well but I can't say I can notice any performance difference from the stock direnv hooks.
Where did you see major performance improvements?

**Comment by romkatv** [comment]
> Just tested it on 1-2 dirs: works well

Thanks for verifying.

> Where did you see major performance improvements?

The difference on my machine is 2.4ms of *command lag*. It's not detectable by its own but its 24% of the whole *command lag* budget. A few more things like that and you'll feel prompt lag. I'm using latency terms and thresholds from https://github.com/romkatv/zsh-bench here.

**Comment by infokiller** [comment]
Yeah, these milliseconds add up quickly, and 2.4ms indeed sounds too much for what direnv does.
Thanks for the reference to zsh-bench, looks like another piece of phenomenal work.
