### ISSUE TITLE
Truncate dir in term title

### ISSUE THREAD

**Issue by extremepayne** [romkatv/zsh4humans#9]
Some of the directories I work in are quite long (up to 91 chars), and it's visually annoying to have them cut off (plus, I can't tell exactly where each tab is). I haven't totally migrated to `zsh4humans` yet, but I'm using the snippet with the term title setting and the expansions are beyond me. How would I truncate the dir?

**Comment by romkatv** [comment]
This is documented in http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html. Here are a few examples of truncations you can try. Replace `%~` in your config with one of these:

- `%32<…<%~%<<`
- `%32>…>%~%>>`
- `%3~`
- `%-3~`

Try varying the numeric arguments to see what they do.

You can also truncate the directory using regular Zsh code rather than prompt expansions. For example:

```zsh
function _z4h-set-term-title-precmd() {
  emulate -L zsh
  local dir=${(%):-"%~"}  # ~/foo/bar/baz or /foo/bar/baz
  local parts=("${(@s:/:)dir}")
  local -i from=2 to=$(($#parts - 1))  # values 2 and 1 are tunable parameters
  [[ $dir == /* ]] && (( ++from ))
  (( from <= to )) && parts[from,to]=('…')
  dir=${(j:/:)parts}
  print -rn -- $'\e]0;'${(V)dir}$'\a' >$TTY
}
```

The latter is the most flexible and produces better truncation in my opinion.

**Comment by extremepayne** [comment]
Thanks, those pointers should get me going.
