### ISSUE TITLE
SSH control-master error

### ISSUE THREAD

**Issue by calvinbui** [romkatv/zsh4humans#95]
Running on WSL Ubuntu 20.04

```shell
> ssh user@server.com
muxclient: master hello exchange failed
Failed to connect to new control master
```

However, when using `/bin/ssh` it works perfectly. The remote server runs normal Ubuntu `bash`.

```shell
> /bin/ssh user@server.com
Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-60-generic x86_64)

user@server.com:~$
```

Running `ssh -v` (trimmed):

```shell
debug1: setting up multiplex master socket
debug1: channel 0: new [/.../.ssh/control-master/sock-40b870928b353a139b589d99529dd7de9c282f71]
debug1: control_persist_detach: backgrounding master process
debug1: forking to background
debug1: Entering interactive session.
debug1: pledge: id
debug1: multiplexing control connection
channel_post_mux_listener getpeereid failed: Operation not supported
debug1: mux_client_hello_exchange: read packet failed
muxclient: master hello exchange failed
Failed to connect to new control master
```

The `~/.ssh` folder permissions are:

```shell
> ls -al ~/.ssh/
total 4
drwxrwxrwx 1 user1 user1 4096 Jan 25 02:41 .
drwxrwxrwx 1 user1 user1 4096 Jan 25 02:44 ..
drwx------ 1 user1 user1 4096 Jan 25 02:43 control-master
-rw------- 1 user1 user1 1700 Jan 25 02:15 id_rsa
-rwxrwxrwx 1 user1 user1  189 Jan 12 00:54 known_hosts
```

**Comment by romkatv** [comment]
Odd. I don’t know why that may be. I’m afraid I won’t have the time to look into it for at least a few months.

**Comment by calvinbui** [comment]
Whereabouts is the code? I can dig into myself, but it's like a rabbit-hole right now

**Comment by romkatv** [comment]
The underlying issue is that the following command fails on your machine:

```zsh
command ssh -o ControlMaster=auto -o ControlPersist=5 -o ControlPath=~/.ssh/control-master/sock-%C user@server.com
```

It's supposed to work.

Note that the command doesn't use anything from zsh4humans or even from zsh. You can execute it in any POSIX-like shell.

**Comment by calvinbui** [comment]
Yep there's something going on with WSL. I'll overwrite the `ssh` alias for now.

**Comment by romkatv** [comment]
> I'll overwrite the `ssh` alias for now.

Note this part of zshrc:

```zsh
# Disable automatic teleportation of z4h over ssh when connecting to some-host.
# This makes `ssh some-host` equivalent to `command ssh some-host`.
zstyle ':z4h:ssh:some-host'   passthrough      'yes'
```

If you replace `some-host` with `*`, automatic teleportation via `ssh` will be disabled for all hosts, so typing `ssh user@hostname` will be equivalent to `command ssh user@hostname`.

By the way, this works fine for me on WSL.

**Comment by calvinbui** [comment]
This was on a fresh WSL v1 install of Ubuntu 20.04 if that helps.

I found that if I re-run the SSH command within the control timeout (5 seconds), it picks up the existing file and works:

```shell
> ssh user@server.com
muxclient: master hello exchange failed
Failed to connect to new control master
                                                                                                 
> ssh user@server.com
muxclient: master hello exchange failed                                                                                               
ControlSocket /.../.ssh/control-master/sock-40b870928b353a139b589d99529dd7de9c282f71 already exists, disabling multiplexing       
muxclient: master hello exchange failed                                                                                                          
ControlSocket /.../.ssh/control-master/sock-40b870928b353a139b589d99529dd7de9c282f71 already exists, disabling multiplexing       
                                                                                                                                                 
Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-60-generic x86_64)

user@server.com:~$
```

**Comment by romkatv** [comment]
> This was on a fresh WSL v1 install of Ubuntu 20.04 if that helps.

Works fine for me if that helps.

**Comment by viliusz** [comment]
Apologies for picking up this necro thread. 

Recently I've been experiencing the same issue - getting message `muxclient: master hello exchange failed` on attempt to connect to remote over `ssh`. However, immediate attempt to connect again (within 5 sec window, as stated above) doesn't fail and connection gets established. On second attempt, above message is no longer displayed.

After some digging, it seems that the message would be shown for cases when an expired master socket (in `ControlPath` location) is used to connect to remote. 

An expired master socket would occur in cases when a computer is put to sleep (or hibernate)  after disconnecting from a remote (that had master socket created) and before `ControlPersist` haven't expired yet. When resuming the computer from sleep (or hibernate) and attempting to connect to remote - `ssh` will find the master socket and will attempt to use it for the connection. However, since master socket would be expired - the `ssh` would fail the handshake and display the above message. 

What helped to resolve this - after resuming the computer from sleep (or hibernate) and before connecting to a remote - check for existing master sockets in `ControlPath` and remove those if any exist.

Hope this helps.
